### ISSUE TITLE
Bug exists in dgl-cu111(0.7.0) on CUDA11.1

### ISSUE THREAD

**Issue by hhr114** [dmlc/dgl#3181] opened 2021-07-24 09:39 UTC
## ❓ Questions and Help
When running dgl-examples(torch)/sgc.py on CUDA11.1, the error happens.
Error report:
Traceback (most recent call last):
  File "sgc.py", line 130, in <module>
    main(args)
  File "sgc.py", line 94, in main
    logits = model(g, features) # only compute the train set
  File "/home/hrhe/.conda/envs/220dgl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hrhe/.conda/envs/220dgl/lib/python3.7/site-packages/dgl/nn/pytorch/conv/sgconv.py", line 168, in forward
    if (graph.in_degrees() == 0).any():
  File "/home/hrhe/.conda/envs/220dgl/lib/python3.7/site-packages/dgl/heterograph.py", line 3496, in in_degrees
    deg = self._graph.in_degrees(etid, v_tensor)
  File "/home/hrhe/.conda/envs/220dgl/lib/python3.7/site-packages/dgl/heterograph_index.py", line 578, in in_degrees
    self, int(etype), F.to_dgl_nd(v)))
  File "dgl/_ffi/_cython/./function.pxi", line 287, in dgl._ffi._cy3.core.FunctionBase.__call__
  File "dgl/_ffi/_cython/./function.pxi", line 222, in dgl._ffi._cy3.core.FuncCall
  File "dgl/_ffi/_cython/./function.pxi", line 211, in dgl._ffi._cy3.core.FuncCall3
  File "dgl/_ffi/_cython/./base.pxi", line 155, in dgl._ffi._cy3.core.CALL
dgl._ffi.base.DGLError: [17:32:01] /opt/dgl/src/array/cuda/coo2csr.cu:28: Check failed: e == CUSPARSE_STATUS_SUCCESS: CUSPARSE ERROR: 1
Stack trace:
  [bt] (0) /home/hrhe/.conda/envs/220dgl/lib/python3.7/site-packages/dgl/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x4f) [0x7fb107ea49cf]
  [bt] (1) /home/hrhe/.conda/envs/220dgl/lib/python3.7/site-packages/dgl/libdgl.so(dgl::aten::CSRMatrix dgl::aten::impl::COOToCSR<(DLDeviceType)2, int>(dgl::aten::COOMatrix)+0x885) [0x7fb1087efdd5]
  [bt] (2) /home/hrhe/.conda/envs/220dgl/lib/python3.7/site-packages/dgl/libdgl.so(dgl::aten::COOToCSR(dgl::aten::COOMatrix)+0x43b) [0x7fb107e8630b]
  [bt] (3) /home/hrhe/.conda/envs/220dgl/lib/python3.7/site-packages/dgl/libdgl.so(dgl::UnitGraph::GetInCSR(bool) const+0xc0) [0x7fb1087963a0]
  [bt] (4) /home/hrhe/.conda/envs/220dgl/lib/python3.7/site-packages/dgl/libdgl.so(dgl::UnitGraph::GetFormat(dgl::SparseFormat) const+0x4d) [0x7fb10879740d]
  [bt] (5) /home/hrhe/.conda/envs/220dgl/lib/python3.7/site-packages/dgl/libdgl.so(dgl::UnitGraph::InDegrees(unsigned long, dgl::runtime::NDArray) const+0x36) [0x7fb108798906]
  [bt] (6) /home/hrhe/.conda/envs/220dgl/lib/python3.7/site-packages/dgl/libdgl.so(dgl::HeteroGraph::InDegrees(unsigned long, dgl::runtime::NDArray) const+0x46) [0x7fb1086a1e86]
  [bt] (7) /home/hrhe/.conda/envs/220dgl/lib/python3.7/site-packages/dgl/libdgl.so(+0xdb2579) [0x7fb1086aa579]
  [bt] (8) /home/hrhe/.conda/envs/220dgl/lib/python3.7/site-packages/dgl/libdgl.so(DGLFuncCall+0x48) [0x7fb108637e88]

**Comment by VoVAllen** [comment] 2021-07-24 12:33
How did you install dgl and torch, by pip or conda for each? Also are there multiple cudas on your machine?

**Comment by hhr114** [comment] 2021-07-24 13:29
I have tried both conda and pip for dgl;
I used pip to install torch, and tried torch 1.7 and 1.9.
Last, the results of `nvidia-smi`:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.04    Driver Version: 455.23.04    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    Off  | 00000000:1A:00.0 Off |                  N/A |
| 30%   32C    P8    22W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 3090    Off  | 00000000:1B:00.0 Off |                  N/A |
| 30%   33C    P8    19W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 3090    Off  | 00000000:3D:00.0 Off |                  N/A |
| 30%   31C    P8    16W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 3090    Off  | 00000000:3E:00.0 Off |                  N/A |
| 30%   31C    P8    22W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  GeForce RTX 3090    Off  | 00000000:88:00.0 Off |                  N/A |
| 30%   32C    P8    15W / 350W |   1507MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  GeForce RTX 3090    Off  | 00000000:89:00.0 Off |                  N/A |
| 30%   32C    P8    21W / 350W |   1507MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  GeForce RTX 3090    Off  | 00000000:B1:00.0 Off |                  N/A |
| 30%   32C    P8    28W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  GeForce RTX 3090    Off  | 00000000:B2:00.0 Off |                  N/A |
| 30%   32C    P8    24W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Comment by VoVAllen** [comment] 2021-07-26 07:31
Could you run `torch.version.cuda` in python to see whether it's 11.1?

**Comment by hhr114** [comment] 2021-07-26 08:46
> Could you run `torch.version.cuda` in python to see whether it's 11.1?

Yes, it is.
Btw, I think you may want to focus on the following lines.
>   File "/home/hrhe/.conda/envs/dgl/lib/python3.9/site-packages/dgl/nn/pytorch/conv/sgconv.py", line 168, in forward
    if (graph.in_degrees() == 0).any():
  File "/home/hrhe/.conda/envs/dgl/lib/python3.9/site-packages/dgl/heterograph.py", line 3496, in in_degrees
    deg = self._graph.in_degrees(etid, v_tensor)


```
Traceback (most recent call last):
  File "/home/hrhe/Graph/dgl_examples/sgc/sgc.py", line 130, in <module>
    main(args)
  File "/home/hrhe/Graph/dgl_examples/sgc/sgc.py", line 94, in main
    logits = model(g, features) # only compute the train set
  File "/home/hrhe/.conda/envs/dgl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hrhe/.conda/envs/dgl/lib/python3.9/site-packages/dgl/nn/pytorch/conv/sgconv.py", line 168, in forward
    if (graph.in_degrees() == 0).any():
  File "/home/hrhe/.conda/envs/dgl/lib/python3.9/site-packages/dgl/heterograph.py", line 3496, in in_degrees
    deg = self._graph.in_degrees(etid, v_tensor)
  File "/home/hrhe/.conda/envs/dgl/lib/python3.9/site-packages/dgl/heterograph_index.py", line 577, in in_degrees
    return F.from_dgl_nd(_CAPI_DGLHeteroInDegrees(
  File "dgl/_ffi/_cython/./function.pxi", line 287, in dgl._ffi._cy3.core.FunctionBase.__call__
  File "dgl/_ffi/_cython/./function.pxi", line 222, in dgl._ffi._cy3.core.FuncCall
  File "dgl/_ffi/_cython/./function.pxi", line 211, in dgl._ffi._cy3.core.FuncCall3
  File "dgl/_ffi/_cython/./base.pxi", line 155, in dgl._ffi._cy3.core.CALL
dgl._ffi.base.DGLError: [16:43:32] /opt/dgl/src/array/cuda/coo2csr.cu:28: Check failed: e == CUSPARSE_STATUS_SUCCESS: CUSPARSE ERROR: 1
```

**Comment by VoVAllen** [comment] 2021-07-26 08:55
It's weird. We have fully tested such functions. Previously this function is related to the cub namespace collision with pytorch. But this should be fully fixed in dgl 0.7. Could you try `dgl.__version__` to see whether it's 0.7? The error code is saying `CUSPARSE_STATUS_NOT_INITIALIZED` but I don't know why this happens on your code.

**Comment by VoVAllen** [comment] 2021-07-26 08:55
Could you post the full code snippet?

**Comment by hhr114** [comment] 2021-07-26 08:57
> It's weird. We have fully tested such functions. Previously this function is related to the cub namespace collision with pytorch. But this should be fully fixed in dgl 0.7. Could you try `dgl.__version__` to see whether it's 0.7? The error code is saying `CUSPARSE_STATUS_NOT_INITIALIZED` but I don't know why this happens on your code.

```
>>> dgl.__version__
'0.7.0'
```

**Comment by hhr114** [comment] 2021-07-26 08:59
> Could you post the full code snippet?

I used the same code as that in https://github.com/dmlc/dgl/tree/master/examples/pytorch/sgc and ran it following ReadMe.md.
I changed nothing.

**Comment by VoVAllen** [comment] 2021-08-02 09:23
I cannot reproduce the error at my side. Could you provide more information about your system or a reproducible docker image?
Also you may want to check the environment variables such as `LD_LIBRARY_PATH`

**Closed** 2021-08-09 07:55 UTC
