### ISSUE TITLE
ModuleNotFoundError: No module named 'dgl.graph'

### ISSUE THREAD

**Issue by Chokerino** [dmlc/dgl#2470] opened 2020-12-30 09:31 UTC
OS - Windows 10
Pytorch - 1.7.1
Tensorflow - 2.3.0
DGl - 0.5.3
CUDA - 11.0
If i try to load dgl graphs using my code i get this error.
```
File "model_bind5.py", line 85, in <module>
    model = pickle.load(fp)
ModuleNotFoundError: No module named 'dgl.graph'
```
This started after i installed the CUDA version of dgl. How to fix this?

**Comment by jermainewang** [comment] 2021-01-04 09:49
Duplicate of https://discuss.dgl.ai/t/modulenotfounderror-no-module-named-dgl-graph/1662

**Closed by jermainewang** 2021-01-04 09:49 UTC
