### ISSUE TITLE
DGL metapath_reachable_graph: unable to allocate 61.0 GiB for an array with sahpe (8185718168,) and data type int64

### ISSUE THREAD

**Issue by stupidoge** [dmlc/dgl#6218] opened 2023-08-28 01:24 UTC
When i am tring to change a big graph into similar and small homographs, there was an error/

the way i am using is:
```
for mp in tqdm(mata_paths):
    homo_graph.append(dgl.metapath_reachable_graph(g, mp)
```
where the meta_paths, is the metapath defined by my self, which strats from entity that I want to classify and end to the same entity. Just like HAN, want to get the metapath based neighbors.

The error is:
```
file data_transformation.oy
    homo_graph.append(dgl.metapath_reachable_graph(g, mp)
File "...dgl/transformsfunctional.py", line 1520, in metapath_reachable_graph
adj = adj * g.adj_external(
File "/usr/local/.../sparse/_base.py", line 590, in _mul_
return self._mul_dispatch(other)
File ",,,_base.py", line 529, in _mul_sparse_matrix
indices = np.empty(nnz, dtype=idx_dtype)
numpy.core._exceptions.MemoryError: Unable to allocate 61.0 GiB for an array with shape (8185718168,) and data type int 64
```

sometimes, the error is ```Killed```

**Comment by jermainewang** [comment] 2023-08-30 16:18
duplicate of https://discuss.dgl.ai/t/dgl-metapath-reachable-graph-unable-to-allocate-xxx-gib-tib-for-an-array-with-sahpe-xxxxxxxxxxxxxxxxx-and-data-type-int64/3945/6

**Closed by jermainewang** 2023-08-30 16:18 UTC
