### ISSUE TITLE
[Bug] Build fail when BUILD_SPARSE=ON

### ISSUE THREAD

**Issue by chang-l** [dmlc/dgl#4923] opened 2022-11-19 00:57 UTC
## 🐛 Bug
Recently, we cannot build from source together with dgl-sparse lib. 
I believe this is due to this PR: https://github.com/dmlc/dgl/pull/4877, where it removes some macro defs probably suffered from multiple definition as here: https://github.com/dmlc/dgl/blob/c8ea9fa4e4afd3d16d86afa99494095060685c10/dgl_sparse/include/sparse/dgl_headers.h#L20-L40

However, the problem is, if users build backend pytorch with flag `USE_GLOG=OFF`, then the DGL build will fail because many check ops are not defined in `c10/util/logging_is_not_google_glog.h`. 

I am wondering why not just replace all check ops in `src/sparse_matrix.cc` to `TORCH_CHECK_OPS` to avoid any confusion?

## To Reproduce

1. Build pytorch with `USE_GLOG=OFF`
2. Build DGL with `BUILD_SPARSE=ON`

Err msg:
```
/workspace/dgl/dgl_sparse/src/sparse_matrix.cc: In constructor 'dgl::sparse::SparseMatrix::SparseMatrix(const std::shared_ptr<dgl::sparse::COO>&, const std::shared_ptr<dgl::sparse::CSR>&, const std::shared_ptr<dgl::sparse::CSR>&, at::Tensor, const std::vector<long int>&)':
/workspace/dgl/dgl_sparse/src/sparse_matrix.cc:26:3: error: 'CHECK_EQ' was not declared in this scope; did you mean 'CHECK_IF'?
   26 |   CHECK_EQ(shape.size(), 2)
      |   ^~~~~~~~
      |   CHECK_IF
```

## Environment

 - DGL Version (e.g., 1.0): 1.0
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): 1.13
 - OS (e.g., Linux): ubuntu
 - How you installed DGL (`conda`, `pip`, source): source

**Comment by czkkkkkk** [comment] 2022-11-19 09:46
* This is an issue when building the sparse library with Pytorch v1.13, which provides unified logging macros like `TORCH_CHECK_EQ`. Previous Pytorch versions are fine because they have GLOG macros defined in both`logging_is_not_google_glog.h` and `logging_is_google_glog.h`. We may need a solution to migrate to Pytorch v1.13. A workaround for now is to build Pytorch with GLOG.
* We still need to un-define GLOG macros introduced by DGL headers because they will cause conflicts when including both DGL and Pytorch headers. (It is still an issue for Pytorch v1.13 if it is built with GLOG)

**Comment by chang-l** [comment] 2022-11-22 01:13
If I understand it correctly, would it make sense to use `TORCH_CHECK_OPS` whenever they are available, otherwise fallback to glog check ops? 

I mean, for example in `sparse_matrix.cpp` file, check if necessary `TORCH_CHECK_OPS` are defined or not; if yes (torch>=1.13 ?), replace to `TORCH_CHECK_OPS`, if no (torch < 1.13), it should be fine with glog check ops. 

Would that work for different pytorch versions built with `USE_GLOG=OFF/ON`?

**Comment by czkkkkkk** [comment] 2022-11-22 03:45
> If I understand it correctly, would it make sense to use TORCH_CHECK_OPS whenever they are available, otherwise fallback to glog check ops?

Yes. I think we will use `TORCH_CHECK_OPS` in the end. To be compatible with old Pytorch version, we may redefine `TORCH_CHECK_OPS` to glog `CHECK_OPS` if Pytorch version is older than 1.13. The redefinitions will be in one file instead of having torch version check in each CHECK or LOG usage.

**Comment by yaox12** [comment] 2022-12-29 08:00
This issue occurs again due to https://github.com/dmlc/dgl/pull/5082. cc @jermainewang @mufeili

**Comment by czkkkkkk** [comment] 2022-12-29 08:15
What is the error message?

**Comment by czkkkkkk** [comment] 2022-12-29 08:22
I reproduced the error. Will make a fix.

**Closed** 2022-12-29 09:35 UTC
