### ISSUE TITLE
c++ API 

### ISSUE THREAD

**Issue by a1372422617** [dmlc/dgl#4131] opened 2022-06-16 01:24 UTC
## ❓ Questions and Help

If I want to write c++ to complete some functions, I need to call some properties of DGL's underlying c++, for example, I need to use dgl::runtime::NDArray, how do I need to call

**Comment by mufeili** [comment] 2022-06-16 04:20
Duplicate of https://discuss.dgl.ai/t/use-of-the-c-api/3010/2

**Closed by mufeili** 2022-06-16 04:20 UTC
