### ISSUE TITLE
What is the difference between dgl 0.6.0.post1 and 0.6.0?

### ISSUE THREAD

**Issue by LukeLIN-web** [dmlc/dgl#5896] opened 2023-06-22 14:26 UTC
I am trying to install dgl 0.6.0, but I have some problems.

1. What is the difference between dgl 0.6.0.post1 and 0.6.0?
2. How to install the cuda version from pip or conda? pip install dgl==0.6.0 is the CPU version.
3. Does it support cuda11.3?
4. `apt-get install -y build-essential python3-dev` will install python3.6, should his version be the same as the original python 3.8 ?

**Comment by mufeili** [comment] 2023-06-29 02:31
Duplicate of https://discuss.dgl.ai/t/what-is-the-difference-between-dgl-0-6-0-post1-and-0-6-0/3766/2

**Closed by mufeili** 2023-06-29 02:31 UTC
