### ISSUE TITLE
Memory leak when using GATConv to process heterogeneous graph

### ISSUE THREAD

**Issue by STQ-AmadeusUser** [dmlc/dgl#3551] opened 2021-11-27 13:21 UTC
## 🐛 Bug

Hello, i am using GATConv from dgl.nn.pytorch.conv to process my heterogeneous graph data. However, i encounter the memory leak problem, where my GPU's memory keeps growing.
Details are as follows:

- I have built a model in order to fulfill a computer vision task with the help of graph structure. However, due to the variety of images, each image in a batch will have unique graph structure. Therefore, in the forward() function in my pytorch model, I extract each graph from each image in a batch and use dgl.batch() function to wrap them into one large graph.
- The large graph i get above is heterogeneous, the canonical_etypes are as follows:
    `(('b', 'positive', 'a'), ('b', 'negative', 'a'), ('a', 'positive', 'a'), ('a', 'negative', 'a'),
          ('a', 'positive', 'b'), ('a', 'negative', 'b'), ('b', 'positive', 'b'), ('b', 'negative', 'b'))`
  It is difficult to deal with the whole graph, so i decide to divide it into subgraph according to the canonical_etype:
`abp_g = graph.edge_type_subgraph([('b', 'positive', 'a')])`
`abn_g = graph.edge_type_subgraph([('b', 'negative', 'a')])`
`aap_g = graph.edge_type_subgraph([('a', 'positive', 'a')])`
`aan_g = graph.edge_type_subgraph([('a', 'negative', 'a')])`
`bap_g = graph.edge_type_subgraph([('a', 'positive', 'b')])`
`ban_g = graph.edge_type_subgraph([('a', 'negative', 'b')])`
`bbp_g = graph.edge_type_subgraph([('b', 'positive', 'b')])`
 and then apply GATConv to process each of above.
 Take abp_g as an example and note that its ndata and edata is empty now:
 `Graph(num_nodes={'a': 338, 'b': 1250},
      num_edges={('b', 'positive', 'a'): 105000},
      metagraph=[('b', 'a', 'positive')])`
- My graph processing model which uses GATConv is as follows:
`from dgl.nn.pytorch.conv import GATConv`
> My graph processing model

    class AttentionAggregator(nn.Module):
        def __init__(self, in_dim=16, hid_dim=8, out_dim=16, num_heads=8, merge='cat'):
            super(AttentionAggregator, self).__init__()
            self.merge = merge
            self.mh_gat = GATConv(in_feats=in_dim, out_feats=hid_dim, num_heads=num_heads, allow_zero_in_degree=True)
            self.fc = nn.Linear(hid_dim*num_heads + in_dim, out_dim)

        def forward(self, g, srcdata, dstdata):
            with g.local_scope():
                emb = self.mh_gat(g, (srcdata, dstdata))
                emb = emb.view(emb.shape[0], -1)
                if self.merge == 'cat':
                    out = torch.cat([emb, dstdata], 1)
                out = self.fc(out)
            del g
            return out
-  I use my model as follows:
  `self.agg_a_from_b_pos = AttentionAggregator(in_dim=16, hid_dim=4, out_dim=16, num_heads=1)`
  `m_a_from_b_pos = self.agg_a_from_b_pos(abp_g, feature_b, feature_a)`
  feature_b.shape is (1250, 16) and feature_a.shape is (338, 16)
  and then i have figured out that this code "self.agg_a_from_b_pos(abp_g, feature_b, feature_a)" will make the memory keep growing with the help of the code below to debug:
  `print("0:{}".format(torch.cuda.memory_allocated(0)))`
  Note that abp_g and feature_b and feature_a will change at each training step. They are dynamic.

## To Reproduce

Sorry! I have not figured out how to write a minimal reproduction.   -_-|||

## Expected behavior

The memory will not keep growing.

## Environment

 - DGL Version: 0.7.2
 - Backend Library & Version: pytorch 1.9
 - OS ubuntu: 18.04
 - How you installed DGL: pip
 - Python version: 3.8
 - CUDA/cuDNN version (if applicable): 10.2
 - GPU models and configuration: 2080Ti
 - Any other relevant information: I have tried the nightly build version but still encounter the problem.
I have experimented dynamic homogeneous graph and the problem disappears.
## Additional context
[SMA_SBG_issue.tar.gz](https://github.com/dmlc/dgl/files/7611773/SMA_SBG_issue.tar.gz)

**Comment by VoVAllen** [comment] 2021-11-27 13:48
Hi,

Could you try add `torch.cuda.empty_cache()` in your code to see whether the problem still exists?

**Comment by ST-QI** [comment] 2021-11-28 06:20
> 

Thanks for your reply! I have added torch.cuda.empty_cache() in my code but the problem still exists ......

**Comment by BarclayII** [comment] 2021-12-02 02:04
So I noticed that you have uploaded a tarball.  Is that all the code needed to reproduce the issue?  I saw that the main file only creates a graph and then stops.

**Comment by ST-QI** [comment] 2021-12-03 09:13
> So I noticed that you have uploaded a tarball. Is that all the code needed to reproduce the issue? I saw that the main file only creates a graph and then stops.

Sorry, those are parts of problem codes in my project instead of all the codes needed to reproduce the issue... 
I haven't write my minimal reproduction.

**Comment by STQ-AmadeusUser** [comment] 2021-12-10 12:29
Hello! Sorry for late implementation!
I encounter the memory leak problem again and make the reproduction in the following link:
[DGL_DEBUG](https://github.com/STQ-AmadeusUser/DGL_DEBUG)
Could you help figure out why my memory keeps growing? @BarclayII @VoVAllen

**Comment by VoVAllen** [comment] 2021-12-13 08:53
@STQ-AmadeusUser Hi, I can reproduce the leak problem. What I saw is about 2MB leak for each epoch. But still in investigation what's the root cause.

**Comment by VoVAllen** [comment] 2021-12-13 09:07
@STQ-AmadeusUser The whole code logic is too complex to me. Did you only see leakage with GAT? What if you try other models? Or try without DGL in your code? Thanks!

**Comment by VoVAllen** [comment] 2021-12-13 09:56
One possible reason could be that some part called forward function without calling backward function later or using `torch.no_grad`.

For the GAT operation, it will cache the graph index, and free it when backward is called. The cache won't be preserved also if `torch.no_grad` is specified. Could you check whether all your forward operations are paired with backward operations, or with `torch.no_grad` configured?

**Comment by STQ-AmadeusUser** [comment] 2021-12-17 14:46
Hello, i have tested TAGConv, GraphConv, EdgeConv and have not found memory leak. The shape of my tensor which is input to GATConv is (64,batch_size,6,6,36). May it be the reason for memory leak?

**Comment by STQ-AmadeusUser** [comment] 2021-12-17 14:54
I think my reproduction has no part of which backward function fails to be called. @VoVAllen

**Comment by STQ-AmadeusUser** [comment] 2021-12-17 16:47
![memory_leak](https://user-images.githubusercontent.com/44997742/146578769-4a2a41ce-f03d-48e0-a269-1b6692d3fb26.png)
I have also used memory_profiler to monitor memory, i found memories of function "self.GAT_body_channel" and "self.GAT_body_spatial" in class ChannelSpatialGATLayer in commom.py keep growing.

**Comment by STQ-AmadeusUser** [comment] 2021-12-17 17:31
Then, i tested the class AttentionAggregator using memory_profiler as well and found the memory display as this picture.
![Screenshot from 2021-12-18 01-25-08](https://user-images.githubusercontent.com/44997742/146584204-334bfc67-9a04-4fea-be29-484725489a2e.png)
Clearly the operation of building a graph and use GATConv will consume memories, but i cannot figure out if the memories are released later.

**Comment by jermainewang** [comment] 2022-08-24 09:08
This may have been fixed by #4249 . Please reopen if the issue still exists.

**Closed by jermainewang** 2022-08-24 09:08 UTC
Labels: bug, PyTorch
