### ISSUE TITLE
Error while loading from networkx if node id is a string

### ISSUE THREAD

**Issue by RamonBeast** [dmlc/dgl#1788] opened 2020-07-10 18:41 UTC
## 🐛 Bug

It might be intended behavior, but I haven't found it explicitly documented: when 2 nodes are connected and at least one node has a `string` as an `id`, conversion to `DGLGraph()` fails.

## To Reproduce

```python
    x = nx.Graph()
    x.add_node('A')
    x.add_node('B')
    x.add_edge('A', 'B')
    x = DGLGraph(x)
```

```
  File "transform.py", line 30, in nx_to_dgl
    x = DGLGraph(x)
  File "/lib/python3.8/site-packages/dgl/graph.py", line 996, in __init__
    gidx = graph_index.create_graph_index(graph_data, readonly)
  File "/lib/python3.8/site-packages/dgl/graph_index.py", line 1262, in create_graph_index
    raise DGLError('Error while creating graph from input of type "%s".'
dgl._ffi.base.DGLError: Error while creating graph from input of type "<class 'networkx.classes.graph.Graph'>".
```

## Expected behavior

Clean conversion from networkx to DGLGraph

## Environment

 - DGL Version: `dgl==0.4.3.post2`
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): `torch==1.5.1`
 - OS (e.g., Linux): Mac OS & Linux
 - How you installed DGL (`conda`, `pip`, source): pip
 - Python version: 3.8.3

**Comment by mufeili** [comment] 2020-07-10 19:52
Try

```python
import networkx as nx
from dgl import DGLGraph

x = nx.Graph()
x.add_node('A')
x.add_node('B')
x.add_edge('A', 'B')
g = DGLGraph()
g.from_networkx(x)
```

**Comment by RamonBeast** [comment] 2020-07-10 22:23
Thanks @mufeili it seems to work on the small test (though I thought it would be the same going from the constructor or from the `from_networkx` method), but it doesn't work on my tiny graph:

```python
import networkx as nx
from networkx.readwrite import json_graph
from dgl import DGLGraph

adj = {"graph": [["id", "619032566627827714"]], "nodes": [{"id": "246141253769494528:4624:1594188859832", "location": "w", "cluster": False, "trigger": True, "pn": "ws"}, {"id": "246141253769494528:4624:1594188859832:E", "location": "", "actions": [65], "cluster": False, "trigger": False, "pn": "E65"}, {"id": "246141253769494528:7920:1594188861018", "location": "w", "cluster": False, "trigger": False, "pn": "cm"}, {"id": "246141253769494528:7920:1594188861018:E", "location": "", "actions": [65], "cluster": False, "trigger": False, "pn": "E65"}, {"id": "246141253769494528:1140:1594188861735", "location": "w", "cluster": False, "trigger": False, "pn": "ps"}, {"id": "246141253769494528:1140:1594188861735:E", "location": "", "actions": [65, 8], "cluster": False, "trigger": False, "pn": "E65 E8"}, {"id": "246141253769494528:1140:1594188861735:C", "location": "", "cluster": True, "trigger": False, "pn": "C2"}], "directed": True, "adjacency": [[{"id": "246141253769494528:4624:1594188859832:E"}, {"id": "246141253769494528:7920:1594188861018"}], [], [{"id": "246141253769494528:7920:1594188861018:E"}, {"id": "246141253769494528:1140:1594188861735:C"}], [], [{"id": "246141253769494528:1140:1594188861735:E"}], [], [{"id": "246141253769494528:1140:1594188861735"}]], "multigraph": False}
x = json_graph.adjacency_graph(adj)
g = DGLGraph()
g.from_networkx(x)
```

Would you know if any of the node properties might be problematic for DGL?
Thank you!

**Comment by RamonBeast** [comment] 2020-07-11 10:55
I ran a few more experiments and I believe there's something weird.

```python
# This example works fine
g = nx.Graph(id='graph')
g.add_node('A')
g.add_node('B')
g.add_edge('B', 'A')
x = DGLGraph()
x.from_networkx(g)
```

We can extract the `adjacency data` from the newly created `g`:

```python
adj_g = json_graph.adjacency_data(g)
```
```python
# Looks like this
{'directed': False,
 'multigraph': False,
 'graph': [('id', 'graph')],
 'nodes': [{'id': 'A'}, {'id': 'B'}],
 'adjacency': [[{'id': 'B'}], [{'id': 'A'}]]}
```

I loaded this same `adjacency data` into a new `networkx graph`:
```python
x = json_graph.adjacency_graph(adj_g)
```

```python
# Let's see the adjacency data
nx.adjacency_data(x)

{'directed': False,
 'multigraph': False,
 'graph': [('id', 'graph')],
 'nodes': [{'id': 'A'}, {'id': 'B'}],
 'adjacency': [[{'id': 'B'}], [{'id': 'A'}]]}
```
They look the same, as they should, let's now convert this graph into `DGL` format:

```python
z = DGLGraph()
z.from_networkx(x)
```

```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/usr/local/lib/python3.8/site-packages/dgl/graph_index.py in create_graph_index(graph_data, readonly)
   1259         try:
-> 1260             gidx = from_networkx(graph_data, readonly)
   1261         except Exception:  # pylint: disable=broad-except

/usr/local/lib/python3.8/site-packages/dgl/graph_index.py in from_networkx(nx_graph, readonly)
   1086             eid = attr['id']
-> 1087             src[eid] = u
   1088             dst[eid] = v

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

During handling of the above exception, another exception occurred:

DGLError                                  Traceback (most recent call last)
```

Ok let's try the other way:

```python
z = DGLGraph(x)
```

```python
/usr/local/lib/python3.8/site-packages/dgl/graph.py in __init__(self, graph_data, node_frame, edge_frame, multigraph, readonly, sort_csr, batch_num_nodes, batch_num_edges, parent)
    994                 dgl_warning("multigraph will be deprecated." \
    995                             "DGL will treat all graphs as multigraph in the future.")
--> 996             gidx = graph_index.create_graph_index(graph_data, readonly)
    997             if sort_csr:
    998                 gidx.sort_csr()

/usr/local/lib/python3.8/site-packages/dgl/graph_index.py in create_graph_index(graph_data, readonly)
   1260             gidx = from_networkx(graph_data, readonly)
   1261         except Exception:  # pylint: disable=broad-except
-> 1262             raise DGLError('Error while creating graph from input of type "%s".'
   1263                            % type(graph_data))
   1264         return gidx

DGLError: Error while creating graph from input of type "<class 'networkx.classes.graph.Graph'>"
```

I'm not sure what's wrong but it seems like loading the `adjacency data` creates issues?

**Comment by mufeili** [comment] 2020-07-11 18:10
See below:

```python
import networkx as nx
from networkx.readwrite import json_graph
from dgl import DGLGraph

# This example works fine
g = nx.Graph(id='graph')
g.add_node('A')
g.add_node('B')
g.add_edge('B', 'A')
print(next(iter(g.edges(data=True)))[-1])
# {}

adj_g = json_graph.adjacency_data(g)
g = json_graph.adjacency_graph(adj_g)
print(next(iter(g.edges(data=True)))[-1])
# {'id': 'A'}
```

There seems to be new edge features added with key `'id'`, which will be used by DGL to specify particular edge ids. For a workaround, you can manually remove that feature for all edges with 

```python
for n1, n2, data in g.edges(data=True):
    del data['id']
print(next(iter(g.edges(data=True)))[-1])
{}
x = DGLGraph()
x.from_networkx(g)
```

**Comment by RamonBeast** [comment] 2020-07-12 09:22
@mufeili it seems to work now on my dataset, many thanks for helping out in solving this.

Do you consider this a bug? If not I'll close the issue.

Again, thank you for your help.

**Comment by mufeili** [comment] 2020-07-14 07:00
@RamonBeast This is an expected behavior, so I will close the issue for the time being.

**Closed by mufeili** 2020-07-14 07:00 UTC
