### ISSUE TITLE
There are something strange when I import dgl , which says "ModuleNotFoundError: No module named 'psutil'"

### ISSUE THREAD

**Issue by zhangnuc** [dmlc/dgl#4447] opened 2022-08-22 12:39 UTC
when I import dgl to use it , it returns a Modu;eNotFoundError , like : "ModuleNotFoundError: No module named 'psutil'"
so I run the command "pip install psutil "in the terminal ,then , I can import dgl normally . 
My question is , Is this situation norm OR just something strange on my environment ? my cuda version is 11.7 , and my cuda toolkit version is 11.3 ,so the version of dgl I pip is "dgl-cuda11.3 ----  0.9.0"

the error returns from my terminal is like the img behinds :
![image](https://user-images.githubusercontent.com/93856240/185922649-675014db-22a2-4e70-abc2-a1d1aadfd7b7.png)

**Comment by yaox12** [comment] 2022-08-23 04:42
Related issue #4300.

**Comment by BarclayII** [comment] 2022-08-23 08:40
Duplicate of #4300.

**Closed** 2022-08-23 08:41 UTC
Labels: triage
