### ISSUE TITLE
Failed to generate libxsmm kernel for the SpMM operation!

### ISSUE THREAD

**Issue by xiangyuwei** [dmlc/dgl#3499] opened 2021-11-14 14:02 UTC
## ❓ Questions and Help

I have the error informaiton:

dgl._ffi.base.DGLError: [21:49:25] /opt/dgl/src/array/cpu/./spmm_blocking_libxsmm.h:267: Failed to generate libxsmm kernel for the SpMM operation!   How to fix it?

**Comment by BarclayII** [comment] 2021-11-15 07:49
Potentially a duplicate of #3476

**Closed by BarclayII** 2021-11-15 07:49 UTC
