### ISSUE TITLE
DGLHeteroGraph: How to add new edge types, especially reverse edges?

### ISSUE THREAD

**Issue by JonnyTran** [dmlc/dgl#2283] opened 2020-10-15 18:48 UTC
## 🚀 Feature
Suppose we have a HeteroGraph G with the following canonical (directed) edge types:

`(‘author’, ‘writes’, ‘paper’), (‘author’, ‘affiliated_with’, ‘institution’), (‘paper’, ‘cites’, ‘paper’), (‘paper’, ‘has_topic’, ‘field_of_study’)
`

I want to add a relation (‘paper’, ‘written_by’, ‘author’) as a reverse of (‘author’, ‘writes’, ‘paper’), however, I’m limited to the following procedures:

```
rel = G.edge_type_subgraph([“writes”])
G.add_edges(*rel.reverse().all_edges(), etype=(‘paper’, ‘written_by’, ‘author’))
```

This would result in the error “DGLError: Edge type “(‘paper’, ‘written_by’, ‘author’)” does not exist.”, making it impossible to add a new edge type to the metagraph.

Is there a way to add a new canonical edge type to an DGL HeteroGraph without instantiating a new one? 
Can we have a new function dgl.add_canonical_edge_type(("A", "B", "C"))?

## Motivation

This feature is very important for heterogeneous networks, since the bipartite subgraph of each relation is directed by default, making certain node types unreachable in the metagraph. Even when trying to traverse the original heterograph using both `dgl.in_subgraph()` and `dgl.out_subgraph()` or `edge_dir="in"` and `edge_dir="out"`, there is still no way to merge the in_subgraph and out_subgraph together.

By adding the reverse relation, we can allow the metagraph to more connected while maintaining the ntype-etype-ntype semantics.

## Alternatives
This function doesn’t solve the problem either, since it only adds reverse edges for a relation which have the same source & target node types.
`dgl.transform.add_reverse_edges(G, ignore_bipartite=True)
`

**Comment by mufeili** [comment] 2020-10-16 03:42
This is a duplicate of [discussion 1408](https://discuss.dgl.ai/t/dglheterograph-how-to-add-new-edge-types-especially-reverse-edges/1408/2).

**Closed** 2021-03-29 07:28 UTC
