### ISSUE TITLE
[Feature] HeteroGraphConv can't handle edge features !!

### ISSUE THREAD

**Issue by rijulizer** [dmlc/dgl#4005] opened 2022-05-13 06:04 UTC
## Feature 
Enhance the dgl.nn.HeteroGraphConv module so that it can consider edge features for various operations.

## Motivation

The current way of using nn.Modules (ex: SageConv) on Heterogeneous graphs, is applying these modules using a wrapper (HeteroGraphConv).  This wrapper applies the mentioned module on individual Bipartite graphs and aggregates the output for a destination node type. However, there is no allocation of edge features in this wrapper. For example, one can not take the existing EGATConv module, which takes the node features and the edge features of the input graph and outputs updated node features, edge features, and attention scores. I want to add a wrapper- HeteroEGATConv which will obliviate this issue. 

## Additional context
We have to also update the EGATConv module to handle bipartite graphs.

**Comment by jermainewang** [comment] 2022-05-16 09:51
Duplicate of https://discuss.dgl.ai/t/handling-edge-features-in-heterographconv-wrapper-for-heterogeneous-graphs/2935. Replied there.

**Closed by jermainewang** 2022-05-16 09:51 UTC
