### ISSUE TITLE
An error occurred when the number of sampling neighbors parameter fan_out was set to -1,-1

### ISSUE THREAD

**Issue by superccy** [dmlc/dgl#2745] opened 2021-03-13 08:48 UTC
Error: 
   socket_communicator.cc:155: Check failed: tmp != -1 (-1 vs. -1)
The data set is Reddit. This error occurred while I was running the distribution.What is the cause of this error?

**Comment by jermainewang** [comment] 2021-03-15 07:39
Could you provide a step-by-step instructions on how to reproduce it? Thanks!

**Comment by superccy** [comment] 2021-03-15 07:57
The example I tested was distributed GraphSage. Since I wanted to run distributed GCN, I changed it to GCN based on GraphSage. The sample of GCN is all neighborhood samples, so I set the parameter fan_out to -1, -1, and this error occurred.

**Comment by superccy** [comment] 2021-03-15 08:07
My guess is that the average degree of the data set Reddit is too large, and the amount of data transmitted by sampling all the neighbors is too large to cause this error. When I make this parameter small or replace a data set with a very small average degree, the program can successfully run.

**Comment by superccy** [comment] 2021-03-15 08:10
My guess is that the average degree of the data set Reddit is too large, and the amount of data transmitted by sampling all the neighbors is too large to cause this error. When I make this parameter small or replace a data set with a very small average degree, the program can successfully run.

**Comment by jermainewang** [comment] 2021-03-18 07:51
Your diagnosis makes sense to me. The issue is then the readability of the error message. @zheng-da Do you have any idea on how to improve this?

**Comment by zheng-da** [comment] 2021-03-22 17:19
I merged a PR that prints more meaningful error messages: https://github.com/dmlc/dgl/pull/2763/files

**Closed** 2021-03-29 07:45 UTC
