### ISSUE TITLE
[Graphbolt] Update OndiskDataset loading logic

### ISSUE THREAD

**Issue by frozenbugs** [dmlc/dgl#6022] opened 2023-07-20 04:19 UTC
## 🔨Work Item

- [x] Pass in directory instead of yaml config.
- [x] 2-step loading, initiation method only load the yaml, add .load() method to trigger actual loading.

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

**Comment by keli-wen** [comment] 2023-08-14 07:37
The issue is finished, maybe we can close it.

**Comment by keli-wen** [comment] 2023-08-14 08:15
Users now need to provide the directory path of the dataset:
```py
dataset = gb.OnDiskDataset(dataset_dir)
```

Unlike previously, where data loading happened during initialization, `OnDiskDataset` now allows users to modify certain settings, such as:
```py
dataset.yaml_data["dataset_name"] = "new_dataset"
```
Afterwards, data is explicitly loaded with `.load()`. By introducing the `_convert_yaml_path_to_absolute_path` function, relative paths in the YAML are converted to absolute paths during the `.load()` call, making it more convenient for users during various operations.

**Closed by keli-wen** 2023-08-14 08:15 UTC
Labels: Work Item
