### ISSUE TITLE
Build fails since mkl not found

### ISSUE THREAD

**Issue by beew** [dmlc/dgl#5474] opened 2023-03-20 22:31 UTC
I am trying to build dgl with pytorch backend from source but it always fails

```
[  8%] Linking CXX shared library libdgl_sparse_pytorch_1.13.1.so
/usr/bin/ld: cannot find -lmkl_intel_ilp64: No such file or directory
/usr/bin/ld: cannot find -lmkl_intel_thread: No such file or directory
/usr/bin/ld: cannot find -lmkl_core: No such file or directory
collect2: error: ld returned 1 exit status
make[5]: *** [CMakeFiles/dgl_sparse_pytorc

```

dgl version v0.4.0-2281-g8a830272

backend pytorch 1.13.1cpu

OS Ubuntu 22.04

python 3.10.9

mkl is in /opt/intel/oneapi/mkl/latest

I have created a mkl.config file in /etc/ld.so.conf.d

```
/opt/intel/oneapi/mkl/latest/lib/intel64
/opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64
```

and it also failed by setting up environmental variables like so

```
export MKLROOT=/opt/intel/oneapi/mkl/latest

export LD_LIBRARY_PATH="$MKLROOT/lib/intel64:$LD_LIBRARY_PATH"

export CPATH="$MKLROOT/include:$CPATH"

export PKG_CONFIG_PATH="$MKLROOT/lib/pkgconfig:$PKG_CONFIG_PATH"

```

I am aware of the quick and dirty way of making symlinks for the .so files to /usr/local/lib (for example), but I think there is a way to set the environmental variables in configurating dgl somehow. I would like to know how to do that.

Thanks.

**Comment by czkkkkkk** [comment] 2023-03-21 14:35
Hi @beew , adding `-DUSE_LIBXSMM=OFF` is a quick fix. We will look into the root cause.

> Does DGL sparse link to MKL by default?

It links to LIBXSMM by default, which uses MKL. I remember @BarclayII checked with the Intel team that LIBXSMM does not strictly require MKL. @BarclayII , do you have any ideas on it?

**Comment by itaraban** [comment] 2023-03-22 10:13
Hi!

As I understand issue appeared during "Linking CXX shared library libdgl_sparse_pytorch_1.13.1.so", so there is no relation to LIBXSMM. 
Probably libtorch added mkl libs during cmake part. It can find mkl on your machine, but unfortunately it will not set up environment. 
Please could you try to run " . /opt/intel/oneapi/setvars.sh" or  ". /opt/intel/oneapi/setvars.sh --force" before building?

**Comment by beew** [comment] 2023-03-27 20:24
Following @itaraban 's advice I did 
```
source /opt/intel/oneapi/setvars.sh
export DGLBACKEND="pytorch"
cmake ..
make -j8
```
```
make -j8
make[3]: warning: -j0 forced in submake: resetting jobserver mode.
[  1%] Building CXX object third_party/dmlc-core/CMakeFiles/dmlc.dir/src/recordio.cc.o
[  2%] Building CXX object third_party/dmlc-core/CMakeFiles/dmlc.dir/src/io.cc.o
[  2%] Building CXX object third_party/dmlc-core/CMakeFiles/dmlc.dir/src/config.cc.o
[  2%] Building CXX object third_party/dmlc-core/CMakeFiles/dmlc.dir/src/data.cc.o
[  2%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/fs-poll.c.o
[  2%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/b64.c.o
[  2%] Building CXX object third_party/dmlc-core/CMakeFiles/dmlc.dir/src/io/line_split.cc.o
[  2%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/blas.c.o
[  2%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/idna.c.o
[  3%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/inet.c.o
[  3%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/random.c.o
[  3%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/strscpy.c.o
[  5%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/threadpool.c.o
[  5%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/timer.c.o
[  5%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/csr.c.o
[  6%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/error.c.o
[  6%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/uv-common.c.o
[  6%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/evaluate.c.o
[  6%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/fkvkselect.c.o
[  7%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/fs.c.o
[  7%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/getopt.c.o
[  7%] Building CXX object third_party/dmlc-core/CMakeFiles/dmlc.dir/src/io/recordio_split.cc.o
[  7%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/gk_util.c.o
[  7%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/uv-data-getter-setters.c.o
[  7%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/gkregex.c.o
[  8%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/graph.c.o
[  8%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/htable.c.o
[ 10%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/version.c.o
[ 10%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/async.c.o
[ 10%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/io.c.o
[ 10%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/core.c.o
[ 11%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/itemsets.c.o
[ 11%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/mcore.c.o
[ 11%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/memory.c.o
[ 12%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/dl.c.o
[ 12%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/fs.c.o
[ 12%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/getaddrinfo.c.o
[ 12%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/getnameinfo.c.o
[ 13%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/loop-watcher.c.o
[ 13%] Building CXX object third_party/dmlc-core/CMakeFiles/dmlc.dir/src/io/indexed_recordio_split.cc.o
[ 13%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/pqueue.c.o
[ 13%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/loop.c.o
[ 15%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/random.c.o
[ 15%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/pipe.c.o
[ 16%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/poll.c.o
[ 16%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/rw.c.o
[ 16%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/seq.c.o
[ 16%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/process.c.o
[ 16%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/random-devurandom.c.o
[ 16%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/signal.c.o
[ 17%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/sort.c.o
[ 18%] Building CXX object third_party/dmlc-core/CMakeFiles/dmlc.dir/src/io/input_split_base.cc.o
[ 18%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/string.c.o
[ 20%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/stream.c.o
[ 20%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/timers.c.o
[ 20%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/__/GKlib/tokenizer.c.o
[ 21%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/auxapi.c.o
[ 21%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/balance.c.o
[ 21%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/bucketsort.c.o
[ 21%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/tcp.c.o
[ 22%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/checkgraph.c.o
[ 22%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/coarsen.c.o
[ 22%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/thread.c.o
[ 22%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/compress.c.o
/home/bernard/src/dgl/third_party/tensorpipe/third_party/libuv/src/unix/thread.c: In function ‘thread_stack_size’:
/home/bernard/src/dgl/third_party/tensorpipe/third_party/libuv/src/unix/thread.c:195:24: warning: comparison of integer expressions of different signedness: ‘rlim_t’ {aka ‘long unsigned int’} and ‘long int’ [-Wsign-compare]
  195 |       if (lim.rlim_cur >= PTHREAD_STACK_MIN)
      |                        ^~
/home/bernard/src/dgl/third_party/tensorpipe/third_party/libuv/src/unix/thread.c: In function ‘uv_thread_create_ex’:
/home/bernard/src/dgl/third_party/tensorpipe/third_party/libuv/src/unix/thread.c:243:20: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘long int’ [-Wsign-compare]
  243 |     if (stack_size < PTHREAD_STACK_MIN)
      |                    ^
[ 22%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/contig.c.o
[ 24%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/tty.c.o
[ 24%] Building CXX object third_party/dmlc-core/CMakeFiles/dmlc.dir/src/io/filesys.cc.o
[ 24%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/udp.c.o
[ 25%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/debug.c.o
[ 25%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/fm.c.o
[ 25%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/proctitle.c.o
[ 25%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/linux-core.c.o
[ 26%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/linux-inotify.c.o
[ 26%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/fortran.c.o
[ 27%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/frename.c.o
[ 27%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/linux-syscalls.c.o
[ 27%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/procfs-exepath.c.o
[ 29%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/random-getrandom.c.o
[ 29%] Building C object third_party/tensorpipe/tensorpipe/CMakeFiles/tensorpipe_uv.dir/__/third_party/libuv/src/unix/random-sysctl-linux.c.o
[ 29%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/gklib.c.o
[ 29%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/graph.c.o
[ 29%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/initpart.c.o
[ 29%] Linking C static library libtensorpipe_uv.a
[ 29%] Built target tensorpipe_uv
[ 30%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/kmetis.c.o
[ 30%] Building CXX object third_party/dmlc-core/CMakeFiles/dmlc.dir/src/io/local_filesys.cc.o
[ 30%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/kwayfm.c.o
[ 30%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/kwayrefine.c.o
[ 31%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/mcutil.c.o
================================================================================
LIBXSMM master-1.16.1-1534 (Linux@bernard-HP-ProBook-440-G7)
--------------------------------------------------------------------------------
Compiler: Compiler 2023.0.0, Compiler 2023.0.0, and f77 11.3.0
C / C++ target: -msse4.2
Fortran target: -msse4.2
--------------------------------------------------------------------------------
--- LIBXSMM build log
[ 31%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/mesh.c.o
[ 31%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/meshpart.c.o
[ 31%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/minconn.c.o
[ 32%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/mincover.c.o
[ 32%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/mmd.c.o
[ 32%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/ometis.c.o
[ 32%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/options.c.o
[ 34%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/parmetis.c.o
./src/libxsmm_ext.c:178:39: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
  internal_noblas_error("dgemm_batch")(transa_array, transb_array, m_array, n_array, k_array,
                                      ^
./src/libxsmm_ext.c:192:39: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
  internal_noblas_error("sgemm_batch")(transa_array, transb_array, m_array, n_array, k_array,
                                      ^
./src/libxsmm_ext.c:205:33: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
  internal_noblas_error("dgemm")(transa, transb, m, n, k, alpha, a, lda, b, ldb, beta, c, ldc);
                                ^
./src/libxsmm_ext.c:216:33: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
  internal_noblas_error("sgemm")(transa, transb, m, n, k, alpha, a, lda, b, ldb, beta, c, ldc);
                                ^
./src/libxsmm_ext.c:225:33: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
  internal_noblas_error("dgemv")(trans, m, n, alpha, a, lda, x, incx, beta, y, incy);
                                ^
./src/libxsmm_ext.c:234:33: error: passing arguments to a function without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
  internal_noblas_error("sgemv")(trans, m, n, alpha, a, lda, x, incx, beta, y, incy);
                                ^
6 errors generated.
--------------------------------------------------------------
In case of assembler error, perhaps GNU Binutils are outdated.
See https://github.com/hfp/libxsmm#outdated-binutils
--------------------------------------------------------------
make[3]: *** [Makefile:782: obj/intel64/libxsmm_noblas.o] Error 1
make[3]: *** Waiting for unfinished jobs....
[ 34%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/pmetis.c.o
[ 34%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/refine.c.o
[ 35%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/separator.c.o
make[2]: *** [CMakeFiles/libxsmm.dir/build.make:70: CMakeFiles/libxsmm] Error 2
make[1]: *** [CMakeFiles/Makefile2:233: CMakeFiles/libxsmm.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 35%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/sfm.c.o
[ 35%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/srefine.c.o
[ 35%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/stat.c.o
[ 36%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/timing.c.o
[ 36%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/wspace.c.o
[ 36%] Building C object third_party/METIS/libmetis/CMakeFiles/metis.dir/util.c.o
[ 37%] Linking C static library libmetis.a
[ 37%] Built target metis
[ 39%] Linking CXX static library libdmlc.a
[ 39%] Built target dmlc
make: *** [Makefile:136: all] Error 2
```

If I didn't set DGLBACKEND and just did cmake and make (with a flesh git checkout), it complains that it couldn't find torch

```
[100%] Built target dgl
-DCUDA_TOOLKIT_ROOT_DIR= -DTORCH_CUDA_ARCH_LIST= -DUSE_CUDA=OFF -DDGL_INCLUDE_DIRS=/home/bernard/src/dgl/include;/home/bernard/src/dgl/third_party/dlpack/include;/home/bernard/src/dgl/third_party/dmlc-core/include;/home/bernard/src/dgl/third_party/phmap/;/home/bernard/src/dgl/third_party/xbyak/;/home/bernard/src/dgl/third_party/METIS/include/;/home/bernard/src/dgl/tensoradapter/include;/home/bernard/src/dgl/third_party/nanoflann/include;/home/bernard/src/dgl/third_party/libxsmm/include;/home/bernard/src/dgl/third_party/pcg/include;/home/bernard/src/dgl/third_party/METIS/GKlib;/home/bernard/src/dgl/third_party/METIS/include;/home/bernard/src/dgl/third_party/tensorpipe -DDGL_BUILD_DIR=/home/bernard/src/dgl/build
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'
make[2]: *** [CMakeFiles/dgl_sparse.dir/build.make:70: CMakeFiles/dgl_sparse] Error 1
make[1]: *** [CMakeFiles/Makefile2:259: CMakeFiles/dgl_sparse.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

torh was upgraded to 2.0.0, not sure if that is problematic.

I tried the release branch 1.0.1 and encountered this bug
https://github.com/dmlc/dgl/issues/3608

**Comment by beew** [comment] 2023-03-27 22:44
Hi @itaraban 
```
GNU C17 (Ubuntu 11.3.0-1ubuntu1~22.04) version 11.3.0 (x86_64-linux-gnu)
	compiled by GNU C version 11.3.0, GMP version 6.2.1, MPFR version 4.1.0, MPC version 1.2.1, isl version isl-0.24-GMP
```
I am also attaching the error log
[CMakeError.log](https://github.com/dmlc/dgl/files/11083552/CMakeError.log)

**Comment by beew** [comment] 2023-03-27 22:54
Hi, rebuild with gcc 9.5.0, still the same error

**Comment by beew** [comment] 2023-03-28 21:33
@czkkkkkk 

Hi, finally build successfully only with -DUSE_LIBXSMM=OFF

**Comment by itaraban** [comment] 2023-03-28 21:41
Hi!

Unfortunately, we found that libxsmm can use different compiler from what was used in cmake, I'll prepare fix for it in dgl.

**Comment by peizhou001** [comment] 2023-04-06 05:14
Hi @beew , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.

**Comment by peizhou001** [comment] 2023-04-06 05:14
Hi @beew , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.

**Closed by peizhou001** 2023-04-06 05:14 UTC
Labels: bug:confirmed
