### ISSUE TITLE
[RFC] Node/edge type should not be required in subgraph creation when there is only one type 

### ISSUE THREAD

**Issue by mufeili** [dmlc/dgl#1645] opened 2020-06-15 16:03 UTC
## 🚀 Feature

Currently we require specifying the node/edge type for using `DGLHeteroGraph.subgraph` and `DGLHeteroGraph.edge_subgraph`. This shall not be needed if there is only one node/edge type so that we can have a same behavior as `DGLGraph` for homogeneous graphs. What do you think? @BarclayII 

## Demonstration

```python
import dgl
import numpy as np

g = dgl.graph((
    np.array([0, 0, 1, 2]),
    np.array([1, 2, 2, 3])
))
g.subgraph([0])
# AttributeError: 'list' object has no attribute 'get', need to use g.subgraph({'_N': [0]})
g.edge_subgraph([0])
# AttributeError: 'list' object has no attribute 'items', need to use g.edge_subgraph({'_E': [0]})
```

**Comment by BarclayII** [comment] 2020-06-27 10:56
This is a duplicate of #1563 and it should be fixed in #1642.  Please feel free to reopen if it still does not work.

**Closed by BarclayII** 2020-06-27 10:56 UTC
