### ISSUE TITLE
error Expect number of features to match number of nodes (len(u)). Got 1978 and 2000 instead.

### ISSUE THREAD

**Issue by WMX567** [dmlc/dgl#6340] opened 2023-09-17 03:33 UTC
## 🐛 Bug
/home1/mengxiwu/.conda/envs/pyCLGL/lib/python3.7/site-packages/dgl/dataloading/dataloader.py:869: DGLWarning: Dataloader CPU affinity opt is not enabled, consider switching it on (see enable_cpu_affinity() or CPU best practices for DGL [https://docs.dgl.ai/tutorials/cpu/cpu_best_practises.html])
  dgl_warning(f'Dataloader CPU affinity opt is not enabled, consider switching it on '
/home1/mengxiwu/.conda/envs/pyCLGL/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3441: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home1/mengxiwu/.conda/envs/pyCLGL/lib/python3.7/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
{sampler_d_samp_c_node_budget_40_nei_budget_30_lambda_1}
method args are {'sampler': 'd_samp', 'c_node_budget': 40, 'nei_budget': 30, 'lambda': 1}
no_inter_task_edges/cls_IL/train_ratio_0.6/val_Reddit-CL_ssm_GAT_bs2000_['d_samp', 40, 30, 1]_bceTrue_bs2000 0
T00 99.27|acc_mean: 99.27
T00 62.94|T01 97.88|acc_mean: 80.41
T00 55.80|T01 86.23|T02 96.43|acc_mean: 79.49
T00 45.89|T01 76.06|T02 91.53|T03 95.65|acc_mean: 77.28
T00 47.63|T01 50.27|T02 84.82|T03 78.02|T04 96.92|acc_mean: 71.53
T00 67.45|T01 85.31|T02 61.81|T03 78.17|T04 97.45|T05 92.97|acc_mean: 80.53
T00 66.72|T01 78.84|T02 5.16|T03 10.85|T04 62.90|T05 75.84|T06 47.99|acc_mean: 49.76
T00 15.76|T01 58.91|T02 0.22|T03 59.16|T04 46.29|T05 36.38|T06 33.52|T07 0.71|acc_mean: 31.37
T00 0.61|T01 7.87|T02 0.22|T03 0.36|T04 0.00|T05 0.00|T06 0.18|T07 0.00|T08 61.81|acc_mean: 7.89
T00 0.00|T01 3.18|T02 0.00|T03 0.13|T04 0.00|T05 0.00|T06 0.18|T07 0.00|T08 59.00|T09 0.00|acc_mean: 6.25
T00 0.00|T01 0.20|T02 0.00|T03 0.00|T04 0.00|T05 0.00|T06 0.00|T07 0.00|T08 0.00|T09 0.00|T10 50.00|acc_mean: 4.56
T00 0.00|T01 0.00|T02 0.00|T03 0.00|T04 0.00|T05 0.00|T06 0.00|T07 0.00|T08 0.00|T09 0.00|T10 0.00|T11 50.00|acc_mean: 4.17
error Expect number of features to match number of nodes (len(u)). Got 1978 and 2000 instead.
Traceback (most recent call last):
  File "/scratch1/mengxiwu/NLGL/train.py", line 163, in <module>
    AP, AF, acc_matrix = main(args,valid=True)
  File "/scratch1/mengxiwu/NLGL/pipeline.py", line 243, in pipeline_class_IL_no_inter_edge_minibatch
    life_model_ins.observe_class_IL_batch(args, subgraph, dataloader, features, labels, task, train_ids, ids_per_cls, dataset)
  File "/scratch1/mengxiwu/NLGL/Baselines/ssm_model.py", line 82, in observe_class_IL_batch
    output_predictions,_ = self.net.forward_batch(blocks, input_features)
  File "/scratch1/mengxiwu/NLGL/Backbones/gnns.py", line 109, in forward_batch
    logits, e = self.gat_layers[-1].forward_batch(blocks[-1], h)
  File "/scratch1/mengxiwu/NLGL/Backbones/gnnconv.py", line 333, in forward_batch
    block.dstdata.update({'er': er})
  File "/home1/mengxiwu/.conda/envs/pyCLGL/lib/python3.7/_collections_abc.py", line 841, in update
    self[key] = other[key]
  File "/home1/mengxiwu/.conda/envs/pyCLGL/lib/python3.7/site-packages/dgl/view.py", line 99, in __setitem__
    self._graph._set_n_repr(self._ntid, self._nodes, {key: val})
  File "/home1/mengxiwu/.conda/envs/pyCLGL/lib/python3.7/site-packages/dgl/heterograph.py", line 4033, in _set_n_repr
    ' Got %d and %d instead.' % (nfeats, num_nodes))
dgl._ffi.base.DGLError: Expect number of features to match number of nodes (len(u)). Got 1978 and 2000 instead.

## To Reproduce

Codes: https://github.com/QueuQ

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (PyTorch 1.12):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version: 3.9
 - CUDA/cuDNN version (if applicable): cuda/11.6.2
 - GPU models and configuration (e.g. V100): V40

## Additional context

Any idea about this bug? Many thanks!

**Comment by czkkkkkk** [comment] 2023-09-18 05:57
Hi @WMX567, seems the size of your node features of the last GAT layer does not match the number of nodes. You can try to print out their shape during training to figure out which of them is unexpected.

**Comment by WMX567** [comment] 2023-09-18 19:41
This bug does not happen when running on CPU but only for GPUs. It is very weird.

**Comment by czkkkkkk** [comment] 2023-09-19 03:12
It might be hard for us to look into this code. Could you provide a minimal script that can reproduce this problem?

**Comment by WMX567** [comment] 2023-09-19 04:41
Codes: https://github.com/QueuQ

 python train.py --dataset Arxiv-CL \
       --backbone GAT \
       --gpu 0 \
       --epochs 200 \
       --sample_nbs False \
       --minibatch True \
       --batch_size 2000 \
       --repeats 5 \
       --ratio_valid_test 0.1 0.3 \
       --overwrite_result False \
       --perform_testing True

**Comment by czkkkkkk** [comment] 2023-09-21 01:37
We cannot see the code. Looks like it is not an official DGL code. Could you provide a minimal script that can reproduce this problem?

**Comment by WMX567** [comment] 2023-09-21 01:39
Sorry. The codes are here: https://github.com/QueuQ/SSM

**Comment by czkkkkkk** [comment] 2023-10-26 02:16
The code repository is too huge to follow. Could you give a minimum script to reproduce the issue?

**Comment by czkkkkkk** [comment] 2023-11-09 02:08
Hi @WMX567 , I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.

**Closed by czkkkkkk** 2023-11-09 02:08 UTC
