### ISSUE TITLE
JTNN example, RuntimeError: Expected object of backend CPU

### ISSUE THREAD

**Issue by stephenra** [dmlc/dgl#535] opened 2019-05-15 20:38 UTC
## 🐛 Bug

Running `python3 vaetrain_dgl.py` following the [docs for the JTNN training example](https://github.com/dmlc/dgl/tree/master/examples/pytorch/jtnn) results in a `RuntimeError`.

## To Reproduce

The steps enumerated in the docs for training: ```python3 vaetrain_dgl.py``` produces:

```sh
Loading data...
Loading finished.
	Num samples: 220011
	Vocab file: /home/.dgl/jtnn/vocab.txt

Model #Params: 1221K

Traceback (most recent call last):
  File "vaetrain_dgl.py", line 147, in <module>
    train()
  File "vaetrain_dgl.py", line 88, in train
    loss, kl_div, wacc, tacc, sacc, dacc = model(batch, beta)
  File "/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/code/dgl/examples/pytorch/jtnn/jtnn/jtnn_vae.py", line 91, in forward
    self.move_to_cuda(mol_batch)
  File "/code/dgl/examples/pytorch/jtnn/jtnn/jtnn_vae.py", line 53, in move_to_cuda
    move_dgl_to_cuda(t)
  File "/code/dgl/examples/pytorch/jtnn/jtnn/nnutils.py", line 60, in move_dgl_to_cuda
    g.ndata[key] = g.ndata[key].cuda(non_blocking=True)
  File "/home/local/lib/python3.6/site-packages/dgl/view.py", line 60, in __setitem__
    self._graph.set_n_repr({key : val}, self._nodes)
  File "/home/.local/lib/python3.6/site-packages/dgl/graph.py", line 1591, in set_n_repr
    self._node_frame[key] = val
  File "/home/.local/lib/python3.6/site-packages/dgl/frame.py", line 616, in __setitem__
    self.update_data(key, val, inplace=False)
  File "/home/.local/lib/python3.6/site-packages/dgl/frame.py", line 643, in update_data
    self.update_column(key, val, inplace=inplace)
  File "/home/.local/lib/python3.6/site-packages/dgl/frame.py", line 681, in update_column
    fcol.update(self._index, data, inplace)
  File "/home/.local/lib/python3.6/site-packages/dgl/frame.py", line 149, in update
    self.data = F.scatter_row(self.data, idx, feats)
  File "/home/.local/lib/python3.6/site-packages/dgl/backend/pytorch/tensor.py", line 115, in scatter_row
    return data.index_copy(0, row_index, value)
  File "/lib/python3.6/site-packages/torch/tensor.py", line 312, in index_copy
    return self.clone().index_copy_(dim, index, tensor)
RuntimeError: Expected object of backend CPU but got backend CUDA for argument #4 'source'
```

## Environment

 - DGL Version (e.g., 1.0):  0.2
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.0.0
 - OS (e.g., Linux): Tried both RHEL 7.5 and Ubuntu 16.04 LTS
 - How you installed DGL (`conda`, `pip`, source): Tried both `pip` and `conda`
 - Python version: 3.6.7
 - CUDA/cuDNN version (if applicable): CUDA 9.0.176/cuDNN 7.0
 - GPU models and configuration (e.g. V100): Tesla V100-SXM2 32GB

**Comment by BarclayII** [comment] 2019-05-16 01:45
While I did found an inconsistency due to recent interface change (fixed in #536 ), I ran `vaetrain_dgl.py` and did not observe the problem within 10 minutes.

When did the error occur?  Or does it occur on a specific example?

**Comment by stephenra** [comment] 2019-05-16 03:52
Thanks for the response. I found it failed <30s after printing the model params.

**Comment by BarclayII** [comment] 2019-05-16 07:43
Does it occur consistently after <30s?  I still could not reproduce the problem...

Also, could you try building DGL from source and/or upgrading PyTorch to the latest release?

**Comment by stephenra** [comment] 2019-05-16 13:19
@BarclayII Seems to be working now after both building from source (Ubuntu 16.04 LTS) and upgrading PyTorch==1.1. Thanks!

**Closed** 2019-05-16 14:43 UTC
