### ISSUE TITLE
Feature Assignment

### ISSUE THREAD

**Issue by Nishant3815** [dmlc/dgl#5551] opened 2023-04-13 23:54 UTC
## ❓ Questions and Help
![image](https://user-images.githubusercontent.com/17989690/231906599-bf94100f-c279-459f-ad09-eca1b04bab18.png)

Hi, 

This corresponds to sampler.py file in PinSage example (https://github.com/dmlc/dgl/blob/master/examples/pytorch/pinsage/sampler.py):
I am not able to understand why only dst_nodes are getting considered for assignment of features for blocks[-1]. Since features get aggregated, should we not use all the nodes that we get from src ?
For blocks[0], this looks okay.

Thanks 
Nishant

**Comment by mufeili** [comment] 2023-04-14 06:33
Duplicate of https://discuss.dgl.ai/t/feature-assignment-in-pinsage-implementation/3601

**Closed by mufeili** 2023-04-14 06:33 UTC

**Comment by Nishant3815** [comment] 2023-04-14 21:41
Hi, 

Just wanted to check if this would be answered over the discussion thread ?

**Comment by mufeili** [comment] 2023-04-15 05:17
@Nishant3815 I've pinged @BarclayII to take a look, who was the author of the PinSAGE implementation.
