### ISSUE TITLE
Can we choose Edge Parallel or Node Parallel?

### ISSUE THREAD

**Issue by jwwu666** [dmlc/dgl#2369] opened 2020-11-26 06:16 UTC
## ❓ Questions and Help

Hi,
I'm wondering if we can choose the parallel mode (node parallel or edge parallel)? And can we choose whether to use the  g_SpMM or g_SDDMM?

**Comment by yzh119** [comment] 2020-11-26 06:52
Generally speaking, you are using gSDDMM when calling `apply_edges` and gSPMM when calling `update_all`.
However, whether to use edge parallel or node parallel is controlled by DGL, we have some heuristic strategies.

**Comment by yzh119** [comment] 2020-11-26 06:54
May I kindly ask you the motivation to choose parallel mode? It does not change the computation result, performance-wise our default strategy is nearly optimal and gurantees reproducibility.

**Comment by jwwu666** [comment] 2020-11-26 07:00
The DGL.create_formats() is pretty time-consuming.  I want to only use COO format during computation.

**Comment by yzh119** [comment] 2020-11-26 07:07
`g=g.formats()` restricts the graph format.

**Comment by jwwu666** [comment] 2020-11-26 07:11
Does DGL automatically create the desired format, such as creating CSR format?

**Comment by yzh119** [comment] 2020-11-26 07:12
Yes DGL creates CSR/CSC formats in demand.

**Comment by yzh119** [comment] 2020-11-26 07:15
The overhead of `create_formats_` could be amortized if you are training the GNN in a full-batch setting because these formats will only be materialized once are used again and again.
However, it's a reasonable demand when training GNN in mini-batch setting (w/ sampling), however, it's not clear which one of the following is more time consuming:
1. Always use `coo` format during training and invokes COO kernels (not efficient and not reproducible because of atomic operations).
2. Calls `create_formats_` explicitly in collate functions in Dataloader (also make sure that multi-process data loading is activated), the time spent on creating formats could be hidden (overlapped with GNN computaiton).

**Comment by jwwu666** [comment] 2020-11-26 07:28
How can I always use coo format during training and prevent DGL from automatically creating the desired format？

**Comment by yzh119** [comment] 2020-11-26 07:54
As I have mentioned above, you can use `g = g.formats('coo')` to prevent other formats to be created for `g`.
However in the backward stage a reversed graph is created and you have to manually change the following lines:
1. https://github.com/dmlc/dgl/blob/58775ada1f5c830c33be59a9be1229341f7ab56f/python/dgl/backend/pytorch/sparse.py#L74
2. https://github.com/dmlc/dgl/blob/58775ada1f5c830c33be59a9be1229341f7ab56f/python/dgl/backend/pytorch/sparse.py#L135
3. https://github.com/dmlc/dgl/blob/58775ada1f5c830c33be59a9be1229341f7ab56f/python/dgl/backend/pytorch/sparse.py#L155

to `g_rev = g_rev.formats('coo')`, `_gidx = _gidx.formats('coo')`, `_gidx = _gidx.format('coo')` to avoid CSR/CSC formats be created during back propagation stage.

**Comment by yzh119** [comment] 2020-11-26 07:55
Also I suggest you make sure `create_formats_` is the real bottleneck, move it to collate function in dataloader and activates multi-process data loading could always hide the overhead.

**Comment by jermainewang** [comment] 2021-01-28 07:07
Hi @jwwu666 please try out the latest nightly build. The format conversion speed has been significantly improved. I'll close this issue for now.

**Closed by jermainewang** 2021-01-28 07:07 UTC
