### ISSUE TITLE
R-GCN does not work for graphs with 1 or 2 nodes

### ISSUE THREAD

**Issue by tobias-kirschstein** [dmlc/dgl#1636] opened 2020-06-14 11:09 UTC
## 🐛 Bug

The R-GCN implementation does not work for graphs consisting of only 1 or 2 nodes.
Instead, a `RuntimeError` is thrown in both cases. It might be arguable whether an R-GCN makes sense for such small "graphs". However, there is no reason why it should not work, and as it can be seen below, the problem is rather easy to fix.

## To Reproduce

```
import torch

from dgl import DGLGraph
from dgl.nn import RelGraphConv

# Create graph with 1 node
g1 = DGLGraph()
g1.add_nodes(1, data={'x': torch.randn((1, 8))})

# Create graph with 2 nodes and 1 edge
g2 = DGLGraph()
g2.add_nodes(1, {'x': torch.randn((1, 8))})
g2.add_nodes(1, {'x': torch.randn((1, 8))})
g2.add_edge(0, 1, data={'edge_types': torch.tensor([0])})

# Create graph with 3 nodes and 2 edges
g3 = DGLGraph()
g3.add_nodes(1, {'x': torch.randn((1, 8))})
g3.add_nodes(1, {'x': torch.randn((1, 8))})
g3.add_nodes(1, {'x': torch.randn((1, 8))})
g3.add_edge(0, 1, data={'edge_types': torch.tensor([0])})
g3.add_edge(1, 2, data={'edge_types': torch.tensor([0])})

model = RelGraphConv(8, 16, 1, self_loop=True)

def forward(graph):
    node_embeddings = graph.ndata['x']
    edge_types = graph.edata['edge_types'] if 'edge_types' in graph.edata else torch.tensor([])
    model.forward(graph, node_embeddings, edge_types)

forward(g1) # Fails with: RuntimeError: The size of tensor a (8) must match the size of tensor b (16) at non-singleton dimension 1
```

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-44-f92b18268fea> in <module>
> ----> 1 forward(g1)
> 
> <ipython-input-43-59388dd131be> in forward(graph)
>       2     node_embeddings = graph.ndata['x']
>       3     edge_types = graph.edata['edge_types'] if 'edge_types' in graph.edata else torch.tensor([])
> ----> 4     model.forward(graph, node_embeddings, edge_types)
> 
> /opt/anaconda3/lib/python3.7/site-packages/dgl/nn/pytorch/conv/relgraphconv.py in forward(self, g, x, etypes, norm)
>     187             node_repr = g.ndata['h']
>     188             if self.bias:
> --> 189                 node_repr = node_repr + self.h_bias
>     190             if self.self_loop:
>     191                 node_repr = node_repr + loop_message
> 
> RuntimeError: The size of tensor a (8) must match the size of tensor b (16) at non-singleton dimension 1

```
forward(g2) # Fails with: 
RuntimeError: The size of tensor a (2) must match the size of tensor b (16) at non-singleton dimension 0
```

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-45-0cbad8909c0e> in <module>
> ----> 1 forward(g2)
> 
> <ipython-input-43-59388dd131be> in forward(graph)
>       2     node_embeddings = graph.ndata['x']
>       3     edge_types = graph.edata['edge_types'] if 'edge_types' in graph.edata else torch.tensor([])
> ----> 4     model.forward(graph, node_embeddings, edge_types)
> 
> /opt/anaconda3/lib/python3.7/site-packages/dgl/nn/pytorch/conv/relgraphconv.py in forward(self, g, x, etypes, norm)
>     187             node_repr = g.ndata['h']
>     188             if self.bias:
> --> 189                 node_repr = node_repr + self.h_bias
>     190             if self.self_loop:
>     191                 node_repr = node_repr + loop_message
> 
> RuntimeError: The size of tensor a (2) must match the size of tensor b (16) at non-singleton dimension 0

```
forward(g3) # Successful
```

## Expected behavior

For g1, the result should be the sum of self loop and bias term. A dirty way to fix this is to give this case special treatment in the `forward()` method in `relgraphconv.py:185`:
```
            if len(g.nodes()) == 1:
                node_repr = th.zeros((1, self.out_feat), dtype=th.float32)
            else:
                # message passing
                g.update_all(self.message_func, fn.sum(msg='msg', out='h'))
                # apply bias and activation
                node_repr = g.ndata['h']
```

For g2, the message passing should just work as for bigger graphs. The problem is that the generated message has shape (D,) while it should have (1, D). A way to fix this is to catch this case in the `basis_message_func()` method in `relgraphconv.py:136`
```
        if len(msg.shape) == 1:
            msg = msg.unsqueeze(0)
```

## Environment

 - DGL Version: 0.4.3post2
 - Backend Library & Version: PyTorch 1.5.0
 - OS: Windows
 - How you installed DGL: pip
 - Python version: 3.7.3

**Comment by classicsong** [comment] 2020-06-14 15:39
For heterogeneous graph, we usually add reverse edges for two nodes, this can solve the g2 problem.

For g1, the problem is actually zero-degree node problem for RGCN, which is hard to define how to deal with it. One solution is to excludes those nodes during message passing (the node embedding encoder) and use their features when training the decoder.

**Comment by Stonesusu** [comment] 2020-09-27 10:24
I'm also stucking in this problem：

# Define a Heterograph Conv model
import dgl.nn as dglnn

class RGCN(nn.Module):
    def __init__(self, in_feats, hid_feats, out_feats, rel_names):
        super().__init__()

        self.conv1 = dglnn.HeteroGraphConv({
            rel: dglnn.SAGEConv(in_feats, hid_feats,aggregator_type='mean')
            for rel in rel_names}, aggregate='sum')
        self.conv2 = dglnn.HeteroGraphConv({
            rel: dglnn.SAGEConv(hid_feats, out_feats,aggregator_type='mean')
            for rel in rel_names}, aggregate='sum')

    def forward(self, graph, inputs):
        # inputs are features of nodes
        h = self.conv1(graph, inputs)
        h = {k: F.relu(v) for k, v in h.items()}
        h = self.conv2(graph, h)
        return h

g.etypes：
['correlated-by',
 'linked-by',
 'correlate',
 'discover',
 'link',
 'link_1',
 'discovered-by',
 'linked-by_1']

node_features = {'ipv4_id': ipv4_feats,'user_id': user_feats}
h_dict = model(g, node_features)
h_user = h_dict['user_id']

RuntimeError: The size of tensor a (8491) must match the size of tensor b (12107) at non-singleton dimension 0

please help me！ thanks！

**Comment by jermainewang** [comment] 2020-09-28 07:58
Duplicate of https://github.com/dmlc/dgl/issues/2244.

**Closed by jermainewang** 2020-09-28 07:58 UTC
