### ISSUE TITLE
DGL is not compatible with pytorch_lightning in the official SAGE examples since version 0.7.2

### ISSUE THREAD

**Issue by changym3** [dmlc/dgl#3531] opened 2021-11-22 04:37 UTC
## 🐛 Bug

DGL is not compatible with pytorch_lightning in the official examples since version 0.7.2

## To Reproduce

Following the examples in 
https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/train_lightning.py
I want to train the graph model with `pytorch_lightning`  with a single GPU, however it report a DGLError in DGL v0.7.2.

## My Guess
I found that it is because DGL v0.7.2 adds a new feature to make the `NodeDataLoader` to call `sampler.set_epoch` only when `use_ddp` is enable. 
[line link](https://github.com/dmlc/dgl/blob/7b4b8129e310ba577ded511a4a4c2d54bab7357d/python/dgl/dataloading/pytorch/dataloader.py#L684)
```python
if self.use_ddp:
    if self.use_scalar_batcher:
        self.scalar_batcher.set_epoch(epoch)
    else:
        self.dist_sampler.set_epoch(epoch)
else:
    raise DGLError('set_epoch is only available when use_ddp is True.')
```

However, in `pytorch_lightning`, though I'm not famaliar with its internal implementation, I have some guesses from the code pieces below. 
[line link](https://github.com/PyTorchLightning/pytorch-lightning/blob/8ea39d2c8f68cc33273c3431a310a262e2240cf9/pytorch_lightning/loops/fit_loop.py#L216)
```python
if self.trainer.train_dataloader is not None and callable(
    getattr(self.trainer.train_dataloader.sampler, "set_epoch", None)
):
    # set seed for distributed sampler (enables shuffling for each epoch)
    self.trainer.train_dataloader.sampler.set_epoch(self.current_epoch)
```

It seems that it assumes the sampler which has the `set_epoch` method as the distributed sampler ( which is true in pytorch environment, but not true in DGL). So it alway calls `set_epoch` from the DGL sampler even when `use_ddp=False`. 

## the compromise solution

If I replace the offical `dgl.dataloading.NodeDataLoader` with the inherited loader which overwrites the `set_epoch` method. It will work. 
```python
class MyLoader(dgl.dataloading.NodeDataLoader):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    
    def set_epoch(self, epoch):
        if self.use_scalar_batcher:
            self.scalar_batcher.set_epoch(epoch)
        else:
            self.dist_sampler.set_epoch(epoch)
```

So I am curious that whether to check `use_ddp=True` is neccessary?

## Environment

 - DGL Version (e.g., 0.7.2):
 - pytorch_lightning v1.5.2
 - torch v1.10.0

## Detailed Error Information

```
~/.conda/envs/ptorch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in _run(self, model, ckpt_path)
   1193 
   1194         # dispatch `start_training` or `start_evaluating` or `start_predicting`
-> 1195         self._dispatch()
   1196 
   1197         # plugin will finalized fitting (e.g. ddp_spawn will load trained model)

~/.conda/envs/ptorch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in _dispatch(self)
   1272             self.training_type_plugin.start_predicting(self)
   1273         else:
-> 1274             self.training_type_plugin.start_training(self)
   1275 
   1276     def run_stage(self):

~/.conda/envs/ptorch/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py in start_training(self, trainer)
    200     def start_training(self, trainer: "pl.Trainer") -> None:
    201         # double dispatch to initiate the training loop
--> 202         self._results = trainer.run_stage()
    203 
    204     def start_evaluating(self, trainer: "pl.Trainer") -> None:

~/.conda/envs/ptorch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in run_stage(self)
   1282         if self.predicting:
   1283             return self._run_predict()
-> 1284         return self._run_train()
   1285 
   1286     def _pre_training_routine(self):

~/.conda/envs/ptorch/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py in _run_train(self)
   1312         self.fit_loop.trainer = self
   1313         with torch.autograd.set_detect_anomaly(self._detect_anomaly):
-> 1314             self.fit_loop.run()
   1315 
   1316     def _run_evaluate(self) -> _EVALUATE_OUTPUT:

~/.conda/envs/ptorch/lib/python3.8/site-packages/pytorch_lightning/loops/base.py in run(self, *args, **kwargs)
    142         while not self.done:
    143             try:
--> 144                 self.on_advance_start(*args, **kwargs)
    145                 self.advance(*args, **kwargs)
    146                 self.on_advance_end()

~/.conda/envs/ptorch/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py in on_advance_start(self)
    214         ):
    215             # set seed for distributed sampler (enables shuffling for each epoch)
--> 216             self.trainer.train_dataloader.sampler.set_epoch(self.current_epoch)
    217 
    218         # changing gradient according accumulation_scheduler

~/.conda/envs/ptorch/lib/python3.8/site-packages/dgl/dataloading/pytorch/dataloader.py in set_epoch(self, epoch)
    557                 self.dist_sampler.set_epoch(epoch)
    558         else:
--> 559             raise DGLError('set_epoch is only available when use_ddp is True.')
    560 
    561 class EdgeDataLoader:

DGLError: set_epoch is only available when use_ddp is True.
```

**Comment by BarclayII** [comment] 2021-11-23 10:25
PyTorch Lightning assumes that the dataloader is an instance of `DataLoader` class and invokes `set_epoch` since 1.3.5, which is after the example is contributed.  Could you revert your PL back to 1.3.4 and see if it works for you?

If so, then one fix will be changing the NodeDataLoader and EdgeDataLoader to be actual subclasses of DataLoader (currently they are not).

**Comment by Mbaey** [comment] 2021-11-25 09:22
reduce DGL to a lower  Version can help you.
e.g.: DGL Version (e.g., 0.6.1):

**Comment by fmellomascarenhas** [comment] 2021-12-14 18:45
> PyTorch Lightning assumes that the dataloader is an instance of `DataLoader` class and invokes `set_epoch` since 1.3.5, which is after the example is contributed. Could you revert your PL back to 1.3.4 and see if it works for you?
> 
> If so, then one fix will be changing the NodeDataLoader and EdgeDataLoader to be actual subclasses of DataLoader (currently they are not).

Hi, I had the same issue and changing it to 1.3.4 fixed the issue for me. But unfortunately, there is a logger bug in this PL version, and I have to update it. Not sure what I can do to use PL and DGL at the same time. Maybe downgrading to DGL 0.6.1 will help, as suggested by Mbaey

@BarclayII

**Comment by wsjeon** [comment] 2022-01-28 00:23
Any update on this issue?

**Comment by VoVAllen** [comment] 2022-01-28 06:22
@wsjeon We're working on converting DGL's dataloader to inherit PyTorch's dataloader to resolve this issue. Hopefully it will be included in the next release, and hopefully at the mid of Feb.

**Comment by decoherencer** [comment] 2022-03-09 10:33
> Hopefully it will be included in the next release, and hopefully at the mid of Feb.
Is this included in the v0.8 release? Thanks

**Comment by BarclayII** [comment] 2022-03-15 07:30
I'm working on it.  It still has some problem running with multi-GPUs.

**Comment by BarclayII** [comment] 2022-03-15 09:27
@decoherencer While I'm working on cleaning up the existing PyTorch Lightning example (and extending it to multiple GPUs), you can run the existing examples in `examples/pytorch/graphsage/advanced/train_lightning.py`.  I confirmed that it works with PyTorch Lightning 1.5.10.

**Comment by wsjeon** [comment] 2022-03-24 04:22
@BarclayII May I ask which DGL and PyTorch versions were used?

**Comment by decoherencer** [comment] 2022-03-24 04:28
I tested it on dgl 0.8 and torch 1.10 and dgl 0.8 and torch 1.7. works fine.

could I use `test_dataloader` too and pass the whole graph in that function with inference code in `test_step` instead of separate evaluate? any idea how?
I guess the issue with this could be with other sanity check functions in lightning where the same type of data is expected on all functions

**Comment by decoherencer** [comment] 2022-04-02 15:15
@BarclayII will link prediction dataloaders work now? Found this [https://discuss.dgl.ai/t/dataloader-issue-for-link-prediction-task-with-pytorch-lightning-and-dgl/2833](issue)

**Closed** 2022-04-12 09:26 UTC
Labels: feature request
