### ISSUE TITLE
How to fix randomness?

### ISSUE THREAD

**Issue by xinyi-zhao** [dmlc/dgl#1500] opened 2020-05-06 02:50 UTC
I tried a lot of ways including os.environ["OMP_NUM_THREADS"] = '1' and dgl.random.seed(seed)
But the random is also not fixed. So what else can I do ?

**Comment by VoVAllen** [comment] 2020-05-06 16:39
Could you share more information about your code? And which version are you using?

**Comment by xinyi-zhao** [comment] 2020-05-07 02:28
I am using version 0.4.2 now. Sorry for changing the question. And I add this limitation of the random. 
But the results are also not fixed. 
![image](https://user-images.githubusercontent.com/54973520/81247753-620b2300-904d-11ea-9941-1a47a2fac27b.png)
os.environ["OMP_NUM_THREADS"] = '1'

**Comment by xinyi-zhao** [comment] 2020-05-07 02:29
> Could you share more information about your code? And which version are you using?

I am using version 0.4.2 now. Sorry for changing the question. And I add this limitation of the random.
But the results are also not fixed.
![image](https://user-images.githubusercontent.com/54973520/81247813-88c95980-904d-11ea-9fd0-658998c646aa.png)
os.environ["OMP_NUM_THREADS"] = '1'

**Comment by yzh119** [comment] 2020-05-07 03:08
@xinyi-zhao could you please elaborate more on what kind of randomness you are experiencing?  sampling result or the message passing result?

For the first one, set number of threads to 1 should fix the randomness. 
For the second, please refer to my reply in #1471 . The non-determinism comes from atomic operations in dgl kernels.

**Comment by jermainewang** [comment] 2020-09-21 04:42
The non-determinism caused by atomic operations in DGL kernels should be fixed in 0.5. Please try again and report back if problem still exists. Thanks.

**Closed by jermainewang** 2020-09-21 04:42 UTC
