### ISSUE TITLE
How to implement inductive GCN on graph-level classification task?

### ISSUE THREAD

**Issue by Beliefuture** [dmlc/dgl#3834] opened 2022-03-13 05:31 UTC
My task is the **graph-level** but not just the node-level or edge-level classification.

The graphs in the training and testing dataset are not the same. They are different in **the shape of the graph i.e. number of nodes and edges** like the **MiniGCDataset** in the tutorial “[Batched Graph Classification with DGL — DGL 0.2 documentation](https://docs.dgl.ai/en/0.2.x/tutorials/basics/4_batch.html)”. But additionally, I also take **the node’s own feature** into the consideration.

![image](https://user-images.githubusercontent.com/62245023/158046441-9d9ae7f8-5ec5-4efd-9b88-bdc0c2e6f534.png)

Therefore, it does not fit the original setting in the GCN faced with the fixed, single graph. But I find **the size of weight matrix** in the formulation proposed by GCN is not affected by the number of nodes, i.e. **(node feature dimension, output dimension)**. So I am confused about the failure in the inductive learning of GCN. One explanation I heard is **the Laplacian matrix** that matters. But I am not so skilled at the theory. Still, I think it just a slightly different from the **GraphSAGE** with the mean aggregation function.

**Comment by Beliefuture** [comment] 2022-03-13 05:36
I am also confused about the operation on the adjacency matrix in the GCN layer defined by DGL.

I find a related question in the forum. [Are there message-passing layers that can’t be used in graphs different than the ones they were trained in?](https://discuss.dgl.ai/t/are-there-message-passing-layers-that-cant-be-used-in-graphs-different-than-the-ones-they-were-trained-in/914) To my understanding, it replaced the adjacency with the "message passing" functions? Therefore, it belongs to inductive learning?

**Comment by mufeili** [comment] 2022-03-14 08:49
Duplicate of [this discussion thread](https://discuss.dgl.ai/t/how-to-carry-out-the-batch-wise-training-while-using-layer-defined-in-dgl/2773)

**Closed by mufeili** 2022-03-14 08:49 UTC
