### ISSUE TITLE
Problem  CUSPARSE ERROR: 10

### ISSUE THREAD

**Issue by impchai** [dmlc/dgl#6476] opened 2023-10-20 03:16 UTC
Hi, recently i have met a problem. When i try to use dgl-cu110 and pytorch version 1.10.2 to calculate graph learning, there raise a issue like:
y_dis = self.grapg_compute(sub,y_res.permute(0,2,1))
File “/data2/chaihaoye/test/test/fsdd.py”, line 339, in grapg_compute
g.update_all(message_func, reduce_func)
File “/data2/chaihaoye/.local/lib/python3.9/site-packages/dgl/heterograph.py”, line 4686, in update_all
ndata = core.message_passing(g, message_func, reduce_func, apply_node_func)
File “/data2/chaihaoye/.local/lib/python3.9/site-packages/dgl/core.py”, line 283, in message_passing
ndata = invoke_gspmm(g, mfunc, rfunc)
File “/data2/chaihaoye/.local/lib/python3.9/site-packages/dgl/core.py”, line 258, in invoke_gspmm
z = op(graph, x)
File “/data2/chaihaoye/.local/lib/python3.9/site-packages/dgl/ops/spmm.py”, line 170, in func
return gspmm(g, ‘copy_lhs’, reduce_op, x, None)
File “/data2/chaihaoye/.local/lib/python3.9/site-packages/dgl/ops/spmm.py”, line 62, in gspmm
ret = gspmm_internal(g._graph, op,
File “/data2/chaihaoye/.local/lib/python3.9/site-packages/dgl/backend/pytorch/sparse.py”, line 307, in gspmm
return GSpMM.apply(gidx, op, reduce_op, lhs_data, rhs_data)
File “/usr/local/anaconda3/envs/torch-1.13.1-py39/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py”, line 105, in decorate_fwd
return fwd(*args, **kwargs)
File “/data2/chaihaoye/.local/lib/python3.9/site-packages/dgl/backend/pytorch/sparse.py”, line 87, in forward
out, (argX, argY) = _gspmm(gidx, op, reduce_op, X, Y)
File “/data2/chaihaoye/.local/lib/python3.9/site-packages/dgl/sparse.py”, line 157, in _gspmm
_CAPI_DGLKernelSpMM(gidx, op, reduce_op,
File “dgl/_ffi/_cython/./function.pxi”, line 287, in dgl._ffi._cy3.core.FunctionBase.call
File “dgl/_ffi/_cython/./function.pxi”, line 232, in dgl._ffi._cy3.core.FuncCall
File “dgl/_ffi/_cython/./base.pxi”, line 155, in dgl._ffi._cy3.core.CALL
dgl._ffi.base.DGLError: [11:09:19] /opt/dgl/src/array/cuda/spmm.cu:213: Check failed: e == CUSPARSE_STATUS_SUCCESS: CUSPARSE ERROR: 10

my code is defined as:

def grapg_compute(self, g, feature):
    g.ndata['h'] = feature        
    message_func = fn.copy_u(u='h', out='m')          
    reduce_func = fn.sum(msg='m', out='h_neigh')  #        
    g.update_all(message_func, reduce_func)
    
    h = g.ndata['h_neigh']
    return h
I can run the program some time age, but now i cant run the program with the above issue.

**Comment by rudongyu** [comment] 2023-10-26 01:07
duplicate of https://discuss.dgl.ai/t/error-check-failed-e-cusparse-status-success-cusparse-error-10/4062

**Closed by rudongyu** 2023-10-26 01:07 UTC

**Comment by YbjFJ** [comment] 2025-11-02 01:53
hi,i meet this same problem when i try to run the code of some paper。even if i have reached the requirements of the python as the paper said, I still can't run it,and it makes me crazy。Please help me solve this problem if you know, here are some results on the running console。
Using backend: pytorch
predicting model...
Traceback (most recent call last):
  File "D:\论文\hf\符号图卷积网络\代码\SCD-main\main.py", line 171, in <module>
    test(args, construct_local_map(args),3)
  File "D:\论文\hf\符号图卷积网络\代码\SCD-main\main.py", line 127, in test
    output = net.forward_test(input_stu_ids, input_exer_ids, input_knowledge_embs, input_nodes, output_nodes, blocks)
  File "D:\论文\hf\符号图卷积网络\代码\SCD-main\model.py", line 99, in forward_test
    node_emb1 = self.gnet1(blocks[0], node_emb)
  File "D:\anaconda3\envs\scd\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\论文\hf\符号图卷积网络\代码\SCD-main\gnn.py", line 55, in forward
    dstdata = self.mods[etype](rel_graph, (src_inputs[stype], dst_inputs[dtype]), *mod_args.get(etype, ()), **mod_kwargs.get(etype, {}))
  File "D:\anaconda3\envs\scd\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\anaconda3\envs\scd\lib\site-packages\dgl\nn\pytorch\conv\gatconv.py", line 313, in forward
    fn.sum('m', 'ft'))
  File "D:\anaconda3\envs\scd\lib\site-packages\dgl\heterograph.py", line 4849, in update_all
    ndata = core.message_passing(g, message_func, reduce_func, apply_node_func)
  File "D:\anaconda3\envs\scd\lib\site-packages\dgl\core.py", line 322, in message_passing
    ndata = invoke_gspmm(g, mfunc, rfunc)
  File "D:\anaconda3\envs\scd\lib\site-packages\dgl\core.py", line 288, in invoke_gspmm
    z = op(graph, x, y)
  File "D:\anaconda3\envs\scd\lib\site-packages\dgl\ops\spmm.py", line 149, in func
    return gspmm(g, binary_op, reduce_op, x, y)
  File "D:\anaconda3\envs\scd\lib\site-packages\dgl\ops\spmm.py", line 77, in gspmm
    lhs_data, rhs_data)
  File "D:\anaconda3\envs\scd\lib\site-packages\dgl\backend\pytorch\sparse.py", line 503, in gspmm
    return GSpMM.apply(gidx, op, reduce_op, lhs_data, rhs_data)
  File "D:\anaconda3\envs\scd\lib\site-packages\torch\cuda\amp\autocast_mode.py", line 219, in decorate_fwd
    return fwd(*args, **kwargs)
  File "D:\anaconda3\envs\scd\lib\site-packages\dgl\backend\pytorch\sparse.py", line 123, in forward
    out, (argX, argY) = _gspmm(gidx, op, reduce_op, X, Y)
  File "D:\anaconda3\envs\scd\lib\site-packages\dgl\sparse.py", line 162, in _gspmm
    arg_e_nd)
  File "D:\anaconda3\envs\scd\lib\site-packages\dgl\_ffi\_ctypes\function.py", line 190, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "D:\anaconda3\envs\scd\lib\site-packages\dgl\_ffi\base.py", line 64, in check_call
    raise DGLError(py_str(_LIB.DGLGetLastError()))
dgl._ffi.base.DGLError: [09:40:42] C:/Users/Administrator/dgl-0.5/src/array/cuda/spmm.cu:213: Check failed: e == CUSPARSE_STATUS_SUCCESS: CUSPARSE ERROR: 10
