### ISSUE TITLE
About creating heterogeneous graph with networkx

### ISSUE THREAD

**Issue by morningphase** [dmlc/dgl#3661] opened 2022-01-18 11:49 UTC
I'm wondering if there any example showing how to creating heterogeneous graph with networkx?

**Comment by mufeili** [comment] 2022-01-23 16:14
Duplicate of https://discuss.dgl.ai/t/about-create-heterogeneous-graph-with-networkx/2633/2

**Closed by mufeili** 2022-01-23 16:14 UTC
