### ISSUE TITLE
Generate my own samplings block for training

### ISSUE THREAD

**Issue by YijianLiu** [dmlc/dgl#4942] opened 2022-11-23 09:14 UTC
I try to construct blocks by myself using to_block. And we get two blocks but they don't follow by right order for map and renumbering , it will result in that it can't achieve message passing one by one. For example:
**Ours:**
blocks[1].ndata[dgl.NID] {'_N': tensor([ 8, 4, 5, 7, 11])}
blocks[0].ndata[dgl.NID] {'_N': tensor([ 8, 2, 3, 6, 10, 4, 5, 7, 11])}

**Right by Using DataLoader**
blocks[1].ndata[dgl.NID] {'_N': tensor([ 8, 4, 5, 7, 11])}
blocks[0].ndata[dgl.NID] {'_N': tensor([ 8, 4, 5, 7, 11, 2, 3, 6, 10])}
We can see for right dataloader, new numbers {2, 3, 6, 10} is after the previous one map index.
So if we use the first things on graphsage, it will be wrong when conv layer 2 to conv layer1 , any method to solve this.

**Comment by jermainewang** [comment] 2022-11-24 01:20
Duplicate of #4934

**Closed by jermainewang** 2022-11-24 01:20 UTC
