### ISSUE TITLE
Question about the incompatibility of cuda12.1 version with cuda12.0 version on the server

### ISSUE THREAD

**Issue by Claudia-Hello** [dmlc/dgl#7160] opened 2024-02-27 06:34 UTC
Hi all,
I would like to know if the dgl under the cuda12.1 version is not compatible with the cuda12.0 server? Because my server’s cuda version is 12.0 and when I ran the code, there came an error:

Traceback (most recent call last):
File “/home/awp_Admin_ZixCQwyA/gxy/matbench-discovery-1.1.1/models/alignn/train_alignn2.py”, line 11, in
from alignn.config import TrainingConfig
File “/home/awp_Admin_ZixCQwyA/miniconda3/envs/mat/lib/python3.11/site-packages/alignn/config.py”, line 9, in
from alignn.models.modified_cgcnn import CGCNNConfig
File “/home/awp_Admin_ZixCQwyA/miniconda3/envs/mat/lib/python3.11/site-packages/alignn/models/modified_cgcnn.py”, line 5, in

import dgl
File “/home/awp_Admin_ZixCQwyA/miniconda3/envs/mat/lib/python3.11/site-packages/dgl/init.py”, line 14, in
from .backend import backend_name, load_backend # usort: skip
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File “/home/awp_Admin_ZixCQwyA/miniconda3/envs/mat/lib/python3.11/site-packages/dgl/backend/init.py”, line 122, in
load_backend(get_preferred_backend())
File “/home/awp_Admin_ZixCQwyA/miniconda3/envs/mat/lib/python3.11/site-packages/dgl/backend/init.py”, line 51, in load_b
ackend
from …_ffi.base import load_tensor_adapter # imports DGL C library
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File “/home/awp_Admin_ZixCQwyA/miniconda3/envs/mat/lib/python3.11/site-packages/dgl/_ffi/base.py”, line 50, in
_LIB, _LIB_NAME, _DIR_NAME = _load_lib()
^^^^^^^^^^^
File “/home/awp_Admin_ZixCQwyA/miniconda3/envs/mat/lib/python3.11/site-packages/dgl/_ffi/base.py”, line 39, in _load_lib
lib = ctypes.CDLL(lib_path[0])
^^^^^^^^^^^^^^^^^^^^^^^^
File “/home/awp_Admin_ZixCQwyA/miniconda3/envs/mat/lib/python3.11/ctypes/init.py”, line 376, in init
self._handle = _dlopen(self._name, mode)
^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libcudart.so.12: cannot open shared object file: No such file or directory

Looking forward to any answers! Thank you so much!!!

**Comment by jermainewang** [comment] 2024-02-29 01:51
Duplicate of https://discuss.dgl.ai/t/question-about-the-incompatibility-of-cuda12-1-version-with-cuda12-0-version-on-the-server/4254/2

**Closed by jermainewang** 2024-02-29 01:51 UTC
