### ISSUE TITLE
Dude, the pinsage example is buggy

### ISSUE THREAD

**Issue by mliwang** [dmlc/dgl#1523] opened 2020-05-15 00:39 UTC
For sampling, have you checked whether a node has neighbor or not in the "random walk restart" module.
Plus, could you please save checkpoints during the training process. It's very disappointing to see the program interrupted because of a bug but no checkpoints left.

Also, I do hope you add more checks to avoid bugs such as "IndexError: tensors used as indices must be long, byte or bool tensors". The general direction of the codebase is correct but those bugs make users annoyed.

**Comment by yzh119** [comment] 2020-05-15 02:15
Thanks very much for raising this "complain issue", we will verify the behavior of nodes without neighbors.

We apologize for the buggy example, currently, the examples are out of the dgl core package which means there are no unit tests for these codes. It's possible that the code becomes buggy after the upgrade of dgl/pytorch/mxnet/etc but the authors of examples have not updated the code in time. We are considering if there is a way to efficiently maintain the consistency and correctness of dgl examples.

**Comment by BarclayII** [comment] 2020-05-15 03:20
@mliwang There are currently two implementations: one is in `examples/pytorch/recommendation`, which was not maintained for a long time and I plan to remove it today because it is using lots of out-dated interfaces and is not the most efficient.  Another is in `examples/pytorch/pinsage`, which should have addressed the issue of nodes with no neighbors.  The problem of not having checkpoints still exists though.

Which implementation were you referring to?  Thanks.

**Comment by mliwang** [comment] 2020-05-15 03:28
examples/pytorch/recommendation
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"Quan (Andy) Gan"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年5月15日(星期五) 中午11:20
 收件人:&nbsp;"dmlc/dgl"<dgl@noreply.github.com&gt;;
 抄送:&nbsp;"WangRanran"<1969671488@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
 主题:&nbsp;Re: [dmlc/dgl] Dude, the pinsage example is buggy (#1523)

 

 

 
@mliwang There are currently two implementations: one is in examples/pytorch/recommendation, which was not maintained for a long time and I plan to remove it today because it is using lots of out-dated interfaces and is not the most efficient. Another is in examples/pytorch/pinsage, which should have addressed the issue of nodes with no neighbors. The problem of not having checkpoints still exists though.
 
Which implementation were you referring to? Thanks.

**Comment by BarclayII** [comment] 2020-05-15 03:41
Thanks.  Could you check out the implementation in `examples/pytorch/pinsage`?  That one is more efficient, takes less memory, and handles the nodes without neighbors.  Although the new implementation was there two months ago it did not get merged until yesterday.

**Closed** 2020-05-18 07:03 UTC

**Comment by BarclayII** [comment] 2020-05-18 09:09
Please feel free to reopen if the problem is not addressed.
