### ISSUE TITLE
Fix hanging bug when writing data to DistTensor.

### ISSUE THREAD

**Issue by jimjlu99** [dmlc/dgl#4347] opened 2022-08-09 18:00 UTC
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

It is reported that when there was an hanging issue in distributed inference due to the write operation to DistTensor. The bug may have been patched by #4036 . Need to verify the result.

**Comment by Rhett-Ying** [comment] 2022-08-10 05:27
this hang issue could be reproduced with `dgl-cu111==0.8.1` while it works well with `dgl-cu111==0.9.0`. I think it's ok to close this ticket now. This issue is probably related to the hang issue we hit during train(https://github.com/dmlc/dgl/issues/3881) and that issue has already fixed since `0.8.2`.

Machines: 4 x g4dn.metal, 8 trainers for each machine.
Graph: 500M ndoes, 1B edges.

Code:
```
import argparse
import time
import numpy as np
import tqdm
import torch as th
import dgl
from dgl.data import register_data_args

'''

Random graph
"etypes": {
        "edge": 0,
        "edge-rev": 1
    },
    "graph_name": "random",
    "halo_hops": 1,
"ntypes": {
        "node1": 0,
        "node2": 1
    },
    "num_edges": 2000000000,
    "num_nodes": 499999994,
    "num_parts": 4,
'''

def init_func(shape, dtype):
    return th.ones(shape, dtype=dtype)


def dist_inference(g, device):
    print("Full graph RGCN inference on rank~{}".format(g.rank()))

    force_even = True
    batch_size = 1024
    h_in = 50
    h_dim = 10
    h_out = 1
    layers = [th.nn.Linear(h_in, h_in), th.nn.Linear(h_in, h_in)]
    eval_fanout_list = [10, 10]
    num_workers = 0
    x = {}
    for k in g.ntypes:
        x[k] = dgl.distributed.DistTensor((g.number_of_nodes(k), h_in),
                                          dtype=th.float32, name='in-featDT',
                                          part_policy=g.get_node_partition_policy(
                                              k),
                                          persistent=True,
                                          init_func=init_func)

    with th.no_grad():
        for l, layer in enumerate(layers):
            # get the fanout for this layer
            eval_fanout = eval_fanout_list[l]
            y = {}
            for k in g.ntypes:
                y[k] = dgl.distributed.DistTensor((g.number_of_nodes(k), h_in),
                                                  dtype=th.float32, name='h-' +
                                                  str(l),
                                                  part_policy=g.get_node_partition_policy(
                                                      k),
                                                  persistent=True)

            infer_nodes = {}
            for ntype in g.ntypes:
                infer_nodes[ntype] = dgl.distributed.node_split(th.ones((g.number_of_nodes(ntype),), dtype=th.bool),
                                                                partition_book=g.get_partition_book(),
                                                                ntype=ntype, force_even=force_even)
            # need to provide the fanout as a list, the number of layers is one obviously here
            sampler = dgl.dataloading.MultiLayerNeighborSampler([eval_fanout])
            dataloader = dgl.dataloading.DistNodeDataLoader(g, infer_nodes, sampler,
                                                            batch_size=batch_size,
                                                            shuffle=True,
                                                            drop_last=False,
                                                            num_workers=num_workers)

            for iter_l, (input_nodes, output_nodes, blocks) in enumerate(tqdm.tqdm(dataloader)):
                #block = blocks[0].to(device)

                if type(input_nodes) is not dict:
                    # This happens on a homogeneous graph.
                    assert len(g.ntypes) == 1
                    input_nodes = {g.ntypes[0]: input_nodes}

                if type(output_nodes) is not dict:
                    # This happens on a homogeneous graph.
                    assert len(g.ntypes) == 1
                    output_nodes = {g.ntypes[0]: output_nodes}

                #h = {k: x[k][input_nodes[k]].to(device) for k in input_nodes.keys()}
                #h = layer(block, h)
                h = {k: x[k][output_nodes[k]] for k in output_nodes.keys()}
                for k, feat in h.items():
                    h[k] = layer(feat)

                for k in h.keys():
                    # some ntypes might be in the tensor h but are not in the output nodes have empty tensors
                    if k in output_nodes:
                        y[k][output_nodes[k]] = h[k].cpu()

            x = y
            g.barrier()
    return y


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='GCN')
    register_data_args(parser)
    parser.add_argument('--graph_name', type=str, help='graph name')
    parser.add_argument('--ip_config', type=str,
                        help='The file for IP configuration')
    parser.add_argument('--num_gpus', type=int, default=1)
    parser.add_argument('--local_rank', type=int,
                        help='get rank of the process')
    args = parser.parse_args()

    dgl.distributed.initialize(args.ip_config)

    g = dgl.distributed.DistGraph(args.graph_name)

    dev_id = g.rank() % args.num_gpus
    device = th.device('cuda:'+str(dev_id))

    dist_inference(g, device)
```

**Closed by Rhett-Ying** 2022-08-10 05:27 UTC
Labels: Distributed Training, Work Item
