### ISSUE TITLE
Cannot Set Random Seed

### ISSUE THREAD

**Issue by WMX567** [dmlc/dgl#5380] opened 2023-02-24 05:45 UTC
Hi,

When I call dgl.random.seed(seed), I have following errors:

Traceback (most recent call last):
  File "/scratch1/mengxiwu/CLGL/GCGL/train.py", line 121, in <module>
    AP, AF, acc_matrix = main(args,valid=True)
  File "/scratch1/mengxiwu/CLGL/GCGL/pipeline.py", line 315, in pipeline_multi_label
    set_random_seed(args['random_seed'], args['r'])
  File "/scratch1/mengxiwu/CLGL/GCGL/utils.py", line 25, in set_random_seed
    dgl.random.seed(seed+r)
  File "/home1/mengxiwu/.conda/envs/pyCLGL/lib/python3.7/site-packages/dgl/random.py", line 19, in seed
    _CAPI_SetSeed(val)
  File "dgl/_ffi/_cython/./function.pxi", line 295, in dgl._ffi._cy3.core.FunctionBase.__call__
  File "dgl/_ffi/_cython/./function.pxi", line 227, in dgl._ffi._cy3.core.FuncCall
  File "dgl/_ffi/_cython/./function.pxi", line 217, in dgl._ffi._cy3.core.FuncCall3
dgl._ffi.base.DGLError: [21:16:58] /opt/dgl/src/random/random.cc:36: Check failed: e == CURAND_STATUS_SUCCESS: CURAND Error: CURAND_STATUS_INITIALIZATION_FAILED at /opt/dgl/src/random/random.cc:36
Stack trace:
  [bt] (0) /home1/mengxiwu/.conda/envs/pyCLGL/lib/python3.7/site-packages/dgl/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x4f) [0x7f535017030f]
  [bt] (1) /home1/mengxiwu/.conda/envs/pyCLGL/lib/python3.7/site-packages/dgl/libdgl.so(+0x6ad786) [0x7f5350476786]
  [bt] (2) /home1/mengxiwu/.conda/envs/pyCLGL/lib/python3.7/site-packages/dgl/libdgl.so(DGLFuncCall+0x48) [0x7f5350483e58]
  [bt] (3) /home1/mengxiwu/.conda/envs/pyCLGL/lib/python3.7/site-packages/dgl/_ffi/_cy3/core.cpython-37m-x86_64-linux-gnu.so(+0x1795c) [0x7f534fb7195c]
  [bt] (4) /home1/mengxiwu/.conda/envs/pyCLGL/lib/python3.7/site-packages/dgl/_ffi/_cy3/core.cpython-37m-x86_64-linux-gnu.so(+0x17e8b) [0x7f534fb71e8b]
  [bt] (5) python(_PyObject_FastCallKeywords+0x47b) [0x56236056d11b]
  [bt] (6) python(+0x191591) [0x56236056d591]
  [bt] (7) python(_PyEval_EvalFrameDefault+0x7c9) [0x562360580fd9]
  [bt] (8) python(_PyFunction_FastCallKeywords+0xf8) [0x562360550758]

My CUDA version is 11.6
I install dgl with: conda install -c dglteam/label/cu116 dgl
My Pytorch version is 1.13

Many thanks!
Mengxi

**Comment by BarclayII** [comment] 2023-02-24 05:52
Duplicate of #5269.

**Closed by BarclayII** 2023-02-24 05:52 UTC
