### ISSUE TITLE
bug:  "import dgl"

### ISSUE THREAD

**Issue by sunshine8586** [dmlc/dgl#6398] opened 2023-09-29 08:29 UTC
## 🐛 Bug

       When I type and run "import dgl", one error is "json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 23)". In fact, I have tried to install and uninstall DGL several times and this problem persists.
## To Reproduce

1. "conda install -c dglteam dgl"
2. import dgl
3. There is an error occurred: "json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 23)"

(torch116_py37) C:\Users\Administrator>python
Python 3.7.1 (default, Oct 28 2018, 08:39:03) [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dgl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\ljj\soft_install\Anaconda3\envs\torch116_py37\lib\site-packages\dgl\__init__.py", line 14, in <module>
    from .backend import backend_name, load_backend  # usort: skip
  File "F:\ljj\soft_install\Anaconda3\envs\torch116_py37\lib\site-packages\dgl\backend\__init__.py", line 122, in <module>
    load_backend(get_preferred_backend())
  File "F:\ljj\soft_install\Anaconda3\envs\torch116_py37\lib\site-packages\dgl\backend\__init__.py", line 107, in get_preferred_backend
    config_dict = json.load(config_file)
  File "F:\ljj\soft_install\Anaconda3\envs\torch116_py37\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "F:\ljj\soft_install\Anaconda3\envs\torch116_py37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "F:\ljj\soft_install\Anaconda3\envs\torch116_py37\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 23)

## Environment

 - DGL Version (e.g., 1.0):   
    dgl                       1.1.2.cu116              py37_0    dglteam/label/cu116

 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): 
    pytorch                   1.13.1          py3.7_cuda11.6_cudnn8_0    pytorch
   

 - OS (e.g., Linux): window
 
 - How you installed DGL (`conda`, `pip`, source):  
    conda install -c dglteam/label/cu116 dgl
 
 - Build command you used (if compiling from source):
 - Python version: 3.7.1

 - CUDA/cuDNN version (if applicable):
    pytorch-cuda              11.6                 h867d48c_1    pytorch

 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by jermainewang** [comment] 2023-10-07 22:51
Duplicate of https://discuss.dgl.ai/t/import-dgl-json-decoder-jsondecodeerror-extra-data-line-2-column-1-char-23/4017/2 . Likely not a bug of DGL but corruption of the config file.

**Closed by jermainewang** 2023-10-07 22:51 UTC
