### ISSUE TITLE
conv.GATConv got an error "KeyError: 'smax'"

### ISSUE THREAD

**Issue by mrbeann** [dmlc/dgl#1127] opened 2019-12-21 13:38 UTC
When I use `nn.pytorch.conv.GATConv` I got an error 
```
    gcn_out = self.gcn(graph, node_features)
  File "/home/.conda/envs/ac/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/.conda/envs/ac/lib/python3.6/site-packages/dgl/nn/pytorch/conv/gatconv.py", line 111, in forward
    graph.edata['a'] = self.attn_drop(edge_softmax(graph, e))
  File "/home/.conda/envs/ac/lib/python3.6/site-packages/dgl/nn/pytorch/softmax.py", line 163, in edge_softmax
    return EdgeSoftmax.apply(graph, logits, eids)
  File "/home/.conda/envs/ac/lib/python3.6/site-packages/dgl/nn/pytorch/softmax.py", line 51, in forward
    g.apply_edges(fn.e_sub_v('s', 'smax', 'out'))
  File "/home/.conda/envs/ac/lib/python3.6/site-packages/dgl/graph.py", line 2148, in apply_edges
    Runtime.run(prog)
  File "/home/.conda/envs/ac/lib/python3.6/site-packages/dgl/runtime/runtime.py", line 11, in run
    exe.run()
  File "/home/.conda/envs/ac/lib/python3.6/site-packages/dgl/runtime/ir/executor.py", line 335, in run
    self.ret.data = fd_data[col_data]
  File "/home/.conda/envs/ac/lib/python3.6/site-packages/dgl/frame.py", line 612, in __getitem__
    return self.select_column(key)
  File "/home/.conda/envs/ac/lib/python3.6/site-packages/dgl/frame.py", line 635, in select_column
    col = self._frame[name]
  File "/home/.conda/envs/ac/lib/python3.6/site-packages/dgl/frame.py", line 316, in __getitem__
    return self._columns[name]
KeyError: 'smax'
```

When I change it to `GraphConv` the error disappeared. How should I fix the problem?

BTW, it seems the forum is broken, when I want to post this in the forum, it returns 500.

**Comment by VoVAllen** [comment] 2019-12-22 10:15
Forum should be fixed now. Your error seems weird to me, could you try update the dgl to the latest version and see whether the error still exists?

**Comment by mrbeann** [comment] 2019-12-22 13:14
Yeah, I used version 0.4.1 with CUDA 10, quite strange.

**Comment by yzh119** [comment] 2019-12-23 06:27
That's weird.
Could you please provide a code snippet so that we could reproduce this error?

**Comment by jermainewang** [comment] 2020-01-06 02:19
Closed due to inactivity.

**Closed by jermainewang** 2020-01-06 02:19 UTC

**Comment by mrbeann** [comment] 2020-01-09 11:40
Sorry, it caused by the disconnected graph.
