### ISSUE TITLE
Failed to generate libxsmm kernel for the SpMM operation!

### ISSUE THREAD

**Issue by benjianzou** [dmlc/dgl#4428] opened 2022-08-17 08:53 UTC
## To Reproduce

Traceback (most recent call last):
  File "/home/coder/project/project/GraphProject/zgraph-lite/test_gcn.py", line 25, in test_gcn_ogb
    emb, predicted, model_bs = model.train(g.ndata['feat'].to(device),
  File "/home/coder/project/project/GraphProject/zgraph-lite/zgraph/alg/embedding/gcn/gcn.py", line 68, in train
    loss = model.get_loss(blocks, feat_in, label_in)
  File "/home/coder/project/project/GraphProject/zgraph-lite/zgraph/alg/embedding/gcn/gcn.py", line 119, in get_loss
    logits = self.forward(blocks, feat_in)
  File "/home/coder/project/project/GraphProject/zgraph-lite/zgraph/alg/embedding/gcn/gcn.py", line 115, in forward
    h = layer(block, h)
  File "/home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/dgl/nn/pytorch/conv/graphconv.py", line 423, in forward
    graph.update_all(aggregate_fn, fn.sum(msg='m', out='h'))
  File "/home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/dgl/heterograph.py", line 4895, in update_all
    ndata = core.message_passing(g, message_func, reduce_func, apply_node_func)
  File "/home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/dgl/core.py", line 357, in message_passing
    ndata = invoke_gspmm(g, mfunc, rfunc)
  File "/home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/dgl/core.py", line 332, in invoke_gspmm
    z = op(graph, x)
  File "/home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/dgl/ops/spmm.py", line 189, in func
    return gspmm(g, 'copy_lhs', reduce_op, x, None)
  File "/home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/dgl/ops/spmm.py", line 75, in gspmm
    ret = gspmm_internal(g._graph, op,
  File "/home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/dgl/backend/pytorch/sparse.py", line 724, in gspmm
    return GSpMM.apply(gidx, op, reduce_op, lhs_data, rhs_data)
  File "/home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 118, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/dgl/backend/pytorch/sparse.py", line 106, in forward
    out, (argX, argY) = _gspmm(gidx, op, reduce_op, X, Y)
  File "/home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/dgl/sparse.py", line 228, in _gspmm
    _CAPI_DGLKernelSpMM(gidx, op, reduce_op,
  File "dgl/_ffi/_cython/./function.pxi", line 293, in dgl._ffi._cy3.core.FunctionBase.__call__
  File "dgl/_ffi/_cython/./function.pxi", line 239, in dgl._ffi._cy3.core.FuncCall
dgl._ffi.base.DGLError: [16:15:23] /opt/dgl/src/array/cpu/./spmm_blocking_libxsmm.h:267: Failed to generate libxsmm kernel for the SpMM operation!
Stack trace:
  [bt] (0) /home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/dgl/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x4f) [0x7f7e50ea5f5f]
  [bt] (1) /home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/dgl/libdgl.so(void dgl::aten::cpu::SpMMRedopCsrOpt<long, float, dgl::aten::cpu::op::CopyLhs<float>, dgl::aten::cpu::op::Add<float> >(dgl::BcastOff const&, dgl::aten::CSRMatrix const&, dgl::runtime::NDArray, dgl::runtime::NDArray, dgl::runtime::NDArray, dgl::runtime::NDArray, dgl::runtime::NDArray)+0x3d4) [0x7f7e510f32c4]
  [bt] (2) /home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/dgl/libdgl.so(void dgl::aten::cpu::SpMMSumCsrLibxsmm<long, float, dgl::aten::cpu::op::CopyLhs<float> >(dgl::BcastOff const&, dgl::aten::CSRMatrix const&, dgl::runtime::NDArray, dgl::runtime::NDArray, dgl::runtime::NDArray)+0x73) [0x7f7e510f3373]
  [bt] (3) /home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/dgl/libdgl.so(void dgl::aten::cpu::SpMMSumCsr<long, float, dgl::aten::cpu::op::CopyLhs<float> >(dgl::BcastOff const&, dgl::aten::CSRMatrix const&, dgl::runtime::NDArray, dgl::runtime::NDArray, dgl::runtime::NDArray)+0x12f) [0x7f7e5110e97f]
  [bt] (4) /home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/dgl/libdgl.so(void dgl::aten::SpMMCsr<1, long, 32>(std::string const&, std::string const&, dgl::BcastOff const&, dgl::aten::CSRMatrix const&, dgl::runtime::NDArray, dgl::runtime::NDArray, dgl::runtime::NDArray, std::vector<dgl::runtime::NDArray, std::allocator<dgl::runtime::NDArray> >)+0xcd3) [0x7f7e51124cd3]
  [bt] (5) /home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/dgl/libdgl.so(dgl::aten::SpMM(std::string const&, std::string const&, std::shared_ptr<dgl::BaseHeteroGraph>, dgl::runtime::NDArray, dgl::runtime::NDArray, dgl::runtime::NDArray, std::vector<dgl::runtime::NDArray, std::allocator<dgl::runtime::NDArray> >)+0x244e) [0x7f7e51158f5e]
  [bt] (6) /home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/dgl/libdgl.so(+0x6648a0) [0x7f7e511788a0]
  [bt] (7) /home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/dgl/libdgl.so(+0x664eb1) [0x7f7e51178eb1]
  [bt] (8) /home/coder/bin/anaconda3/envs/test_dgl/lib/python3.9/site-packages/dgl/libdgl.so(DGLFuncCall+0x48) [0x7f7e511d0b18]

## Environment

 - DGL Version (e.g., 1.0):0.9.0
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):PyTorch 1.12.1+cu102
 - OS (e.g., Linux):Linux(Ubuntu 20.04)
 - How you installed DGL (`conda`, `pip`, source):pip
 - Build command you used (if compiling from source):
 - Python version:3.9.12
 - CUDA/cuDNN version (if applicable):10.2
 - CPU:Intel(R) Xeon(R) CPU E5-2650 v2
 - GPU models and configuration (e.g. V100):GeForce GTX 1080
 - Any other relevant information:

**Comment by BarclayII** [comment] 2022-08-22 06:29
Duplicate of #3459

**Closed by BarclayII** 2022-08-22 06:29 UTC
