### ISSUE TITLE
Multi label classification

### ISSUE THREAD

**Issue by noycohen100** [dmlc/dgl#2405] opened 2020-12-08 10:21 UTC
Hi,
I try to adjust the example of the "graph classification" tutorial to the scenario of multi-label classification?
Can someone help?
In addition, is it possible to create a vector with weights for each class for each sample?
For example: 
If I have 5 different classes and:
-The labels of sample#1 are class1 and class3, can I create a vector with weights =[0, 0.75, 0, 0.25, 0]?

**Comment by mufeili** [comment] 2020-12-10 04:56
Duplicate of https://discuss.dgl.ai/t/multilabel-classification-model/1579

**Closed by mufeili** 2020-12-10 04:56 UTC
