### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Kyridiculous2** [dmlc/dgl#952] opened 2019-10-24 13:58 UTC
## To Reproduce

1.Just run after pip/conda install

![image](https://user-images.githubusercontent.com/26832000/67492661-56f03700-f6a9-11e9-9682-ccad2a0df759.png)

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by BarclayII** [comment] 2019-10-25 02:13
Did you have CUDA 10.0 and VC2015 runtime installed?

If so, could you locate `dgl.dll` in your Python site-packages directory and run `depends.exe` with it to see which dependencies are missing?

It should look like this if everything works:
![image](https://user-images.githubusercontent.com/2978100/67537798-83d73500-f70f-11e9-8e25-62728058e133.png)

**Comment by Kyridiculous2** [comment] 2019-10-25 02:58
Does it looks like this?
So whats wrong with it ?
![image](https://user-images.githubusercontent.com/26832000/67539874-1b3f8680-f716-11e9-878a-6f239a52111f.png)


By the way , I successfully installed it hours ago before I met this problem, then for some reasons I reinstalled the conda and couldn't install it again, is it because you update the source code just at that time ?

**Comment by BarclayII** [comment] 2019-10-25 03:24
> Does it looks like this?
> So whats wrong with it ?

Looks like DGL could not locate CUBLAS and CUSPARSE 10.0.  Could you make sure if your directory containing CUDA 10 DLLs appears in your `PATH` environment variable?

> 
> By the way , I successfully installed it hours ago before I met this problem, then for some reasons I reinstalled the conda and couldn't install it again, is it because you update the source code just at that time ?

Conda currently does not provide nightly build, so changing source code should not affect the packages there.

**Comment by Kyridiculous2** [comment] 2019-10-25 03:29
I think cuda path is correctly added, since pytorch works just fine...

**Comment by Kyridiculous2** [comment] 2019-10-25 05:32
Sorry I realized that its because of the different cuda version ,cause I'm using cuda 10.1 right now, as you haven't support 10.1 yet?
So when will you support 10.1

**Comment by BarclayII** [comment] 2019-10-25 05:57
For now you have to compile DGL from source if you want CUDA 10.1.

We would support 10.1 before 0.5, possibly in a nightly build, but I currently cannot promise a concrete date.

Marking this as a duplicate of #950

**Comment by Kyridiculous2** [comment] 2019-10-25 05:58
Thank you very much!

**Closed by BarclayII** 2019-10-25 05:57 UTC

**Comment by BarclayII** [comment] 2019-10-25 06:17
Since you are using Windows, I suppose compiling from source is not easy.  If you don't care about CUDA version too much, you can instead degrade your PyTorch CUDA version to 10.0:

```
C:\> conda install -c pytorch pytorch cuda100
```

**Comment by Kyridiculous2** [comment] 2019-10-25 06:20
But don't I need to degrade CUDA to 10.0 firstly?
Thanks for your advice!

**Comment by BarclayII** [comment] 2019-10-25 06:30
Yes.  The command above degrades CUDA to 10.0 as well.
